/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mapub.coprodcoef.entity.enumeration;

import nc.md.model.IEnumValue;
import nc.md.model.impl.MDEnum;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
public class BillStatusEnum extends MDEnum {
    public BillStatusEnum(IEnumValue enumvalue) {
        super(enumvalue);
    }

    public static final BillStatusEnum FREE = MDEnum.valueOf(BillStatusEnum.class, -1);

    public static final BillStatusEnum NOPASS = MDEnum.valueOf(BillStatusEnum.class, 0);

    public static final BillStatusEnum APPROVED = MDEnum.valueOf(BillStatusEnum.class, 1);

    public static final BillStatusEnum APPROVING = MDEnum.valueOf(BillStatusEnum.class, 2);

    public static final BillStatusEnum COMMIT = MDEnum.valueOf(BillStatusEnum.class, 3);

}
