/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mapub.coprodcoef.entity.enumeration;

import nc.md.model.IEnumValue;
import nc.md.model.impl.MDEnum;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 *
 * @author
 * @version NCPrj ??
 */
public class ProductTypeEnum extends MDEnum {
    public ProductTypeEnum(IEnumValue enumvalue) {
        super(enumvalue);
    }

    /**
     * 主产品
     */
    public static final ProductTypeEnum MAINPRODUCT = MDEnum.valueOf(ProductTypeEnum.class, Integer.valueOf(1));

    /**
     * 联产品
     */
    public static final ProductTypeEnum JOINT = MDEnum.valueOf(ProductTypeEnum.class, Integer.valueOf(2));

}
