insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KYQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',null,'N',1,'N','Y',0,null,0,'creationtime','mapub.mapub_costtype.creationtime',null,'N',0,null,'1002Z310000000015KYP',null,1,null,null,null,'N',1,23,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KYR',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bcreatetable',null,'N',1,'N','N',0,null,0,'bcreatetable','mapub.mapub_costtype.bcreatetable',null,'N',0,null,'1002Z310000000015KYP',null,1,null,null,null,'N',0,20,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KYS',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_elementsystem',null,'N',1,'N','Y',0,null,0,'pk_elementsystem','mapub.mapub_costtype.pk_elementsystem',null,'N',1,null,'1002Z310000000015KYP',null,1,'要素体系,code=N','138100105-0002',null,'N',1,8,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KYT',1,-1,null,null,0,1,null,-1,'N',null,-1,'vcostpricesource',null,'N',1,'N','N',0,null,0,'vcostpricesource','mapub.mapub_costtype.vcostpricesource',null,'N',0,null,'1002Z310000000015KYP',null,1,null,null,null,'N',0,14,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KYU',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',0,null,0,'pk_group','mapub.mapub_costtype.pk_group',null,'N',0,null,'1002Z310000000015KYP',null,1,null,null,null,'N',0,2,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KYV',1,-1,null,null,0,1,null,-1,'N',null,-1,'vnote',null,'N',1,'N','Y',0,null,0,'vnote','mapub.mapub_costtype.vnote',null,'N',0,null,'1002Z310000000015KYP',null,1,null,null,null,'N',1,21,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KYW',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',0,null,0,'pk_org','mapub.mapub_costtype.pk_org',null,'N',0,null,'1002Z310000000015KYP',null,1,null,null,null,'N',0,3,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KYX',1,-1,null,null,0,0,null,-1,'N',null,-1,'creator',null,'N',1,'N','Y',0,null,0,'creator','mapub.mapub_costtype.creator',null,'N',0,null,'1002Z310000000015KYP',null,1,'用户,code=N',null,null,'N',1,22,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KYY',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bshrinkfactor',null,'N',1,'N','Y',0,null,0,'bshrinkfactor','mapub.mapub_costtype.bshrinkfactor',null,'N',0,null,'1002Z310000000015KYP',null,1,null,'138100105-0001',null,'N',1,7,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KYZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'vmaterialpricesource',null,'N',1,'N','Y',0,null,0,'vmaterialpricesource','mapub.mapub_costtype.vmaterialpricesource',null,'N',1,null,'1002Z310000000015KYP',null,1,null,null,null,'N',1,12,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZ0',1,-1,null,null,0,1,null,-1,'N',null,-1,'vcosttypecode',null,'N',1,'N','Y',0,null,0,'vcosttypecode','mapub.mapub_costtype.vcosttypecode',null,'N',1,null,'1002Z310000000015KYP',null,1,null,null,null,'N',1,4,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZ1',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',0,null,0,'ts','mapub.mapub_costtype.ts',null,'N',0,null,'1002Z310000000015KYP',null,1,null,null,null,'N',0,26,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZ2',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bscrapfactor',null,'N',1,'N','Y',0,null,0,'bscrapfactor','mapub.mapub_costtype.bscrapfactor',null,'N',0,null,'1002Z310000000015KYP',null,1,null,'138100105-0000',null,'N',1,6,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZ3',1,-1,null,null,0,1,null,-1,'N',null,-1,'vmaterialpricesourcenum',null,'N',1,'N','N',0,null,0,'vmaterialpricesourcenum','mapub.mapub_costtype.vmaterialpricesourcenum',null,'N',0,null,'1002Z310000000015KYP',null,1,null,null,null,'N',0,13,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZ4',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbeginmonth',null,'N',1,'N','Y',0,null,0,'cbeginmonth','mapub.mapub_costtype.cbeginmonth',null,'N',1,null,'1002Z310000000015KYP',null,1,null,null,null,'N',1,16,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZ5',1,-1,null,null,0,1,null,-1,'N',null,-1,'vcosttypename',null,'N',1,'N','Y',0,null,0,'vcosttypename','mapub.mapub_costtype.vcosttypename',null,'N',1,null,'1002Z310000000015KYP',null,1,null,null,null,'N',1,5,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZ6',1,-1,null,null,0,1,null,-1,'N',null,-1,'cendmonth',null,'N',1,'N','Y',0,null,0,'cendmonth','mapub.mapub_costtype.cendmonth',null,'N',0,null,'1002Z310000000015KYP',null,1,null,null,null,'N',1,17,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZ7',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccosttypeid',null,'N',1,'N','N',0,null,0,'ccosttypeid','mapub.mapub_costtype.ccosttypeid',null,'N',0,null,'1002Z310000000015KYP',null,1,null,null,null,'N',0,1,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZ8',1,-1,null,null,0,1,null,-1,'N',null,-1,'vcostpricesourcenum',null,'N',1,'N','N',0,null,0,'vcostpricesourcenum','mapub.mapub_costtype.vcostpricesourcenum',null,'N',0,null,'1002Z310000000015KYP',null,1,null,null,null,'N',0,15,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZ9',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_materialdocview',null,'N',1,'N','Y',0,null,0,'pk_materialdocview','mapub.mapub_costtype.pk_materialdocview',null,'N',0,null,'1002Z310000000015KYP',null,1,'基础档案对照表,code=N',null,null,'N',1,10,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZA',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',null,'N',1,'N','Y',0,null,0,'modifier','mapub.mapub_costtype.modifier',null,'N',0,null,'1002Z310000000015KYP',null,1,'用户,code=N','138100105-0003',null,'N',1,24,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZB',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bcompute',null,'N',1,'N','N',0,null,0,'bcompute','mapub.mapub_costtype.bcompute',null,'N',0,null,'1002Z310000000015KYP',null,1,null,null,null,'N',0,19,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZC',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_factorchart',null,'N',1,'N','Y',0,null,0,'pk_factorchart','mapub.mapub_costtype.pk_factorchart',null,'N',1,null,'1002Z310000000015KYP',null,1,'要素表,code=N',null,null,'N',1,9,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZD',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_activitydocview',null,'N',1,'N','N',0,null,0,'pk_activitydocview','mapub.mapub_costtype.pk_activitydocview',null,'N',0,null,'1002Z310000000015KYP',null,1,null,null,null,'N',0,11,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZE',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',null,'N',1,'N','Y',0,null,0,'modifiedtime','mapub.mapub_costtype.modifiedtime',null,'N',0,null,'1002Z310000000015KYP',null,1,null,'138100105-0004',null,'N',1,25,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015KZF',1,-1,null,'false',0,1,null,-1,'N',null,-1,'bdefault',null,'N',1,'N','N',0,null,0,'bdefault','mapub.mapub_costtype.bdefault',null,'N',0,null,'1002Z310000000015KYP',null,1,null,null,null,'N',0,18,'mapub_costtype','成本类型',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

