insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005HJ7',1,-1,null,null,0,0,null,-1,'N','ccostcenterid',-1,'ccostcenterid.cccode',0,'N',1,'N','N',2,null,0,'cccode','resa.resacostcenter.cccode',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',0,2,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z310000000005HJ8',1,-1,null,null,0,0,null,-1,'N','cbcostcenterid',-1,'cbcostcenterid.cccode',0,'N',1,'N','N',23,null,0,'cccode','resa.resacostcenter.cccode',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',0,23,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLA',1,-1,null,null,0,1,null,-1,'N',null,-1,'finstoragetype',0,'N',1,'N','Y',0,null,0,'finstoragetype','mapub.mapub_acquirepricelog.finstoragetype',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,5,'stdcostprocess_mat','入库类型',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLB',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree7',0,'N',1,'N','Y',0,null,0,'vbfree7','mapub.mapub_acquirepricelog.vbfree7',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,37,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLC',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialid',0,'N',1,'N','N',0,null,0,'cmaterialid','mapub.mapub_acquirepricelog.cmaterialid',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',0,7,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLD',1,-1,null,null,0,1,null,-1,'N',null,-1,'isourcetype',0,'N',1,'N','Y',0,null,0,'isourcetype','mapub.mapub_acquirepricelog.isourcetype',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,'13810200002',null,'N',1,42,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLE',1,-1,null,null,0,1,null,-1,'N',null,-1,'cproductorid',0,'N',1,'N','Y',0,null,0,'cproductorid','mapub.mapub_acquirepricelog.cproductorid',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,'生产厂商(自定义档案),code=N',null,null,'N',1,9,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLF',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree7',0,'N',1,'N','Y',0,null,0,'vfree7','mapub.mapub_acquirepricelog.vfree7',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,17,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLG',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree9',0,'N',1,'N','Y',0,null,0,'vfree9','mapub.mapub_acquirepricelog.vfree9',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,19,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLI',1,-1,null,null,0,1,null,-1,'N',null,-1,'prioritylevel',0,'N',1,'N','Y',0,null,0,'prioritylevel','mapub.mapub_acquirepricelog.prioritylevel',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,41,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbcustomerid',0,'N',1,'N','Y',0,null,0,'cbcustomerid','mapub.mapub_acquirepricelog.cbcustomerid',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,'客户档案,code=N',null,null,'N',1,30,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLK',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree6',0,'N',1,'N','Y',0,null,0,'vbfree6','mapub.mapub_acquirepricelog.vbfree6',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,36,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLL',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree9',0,'N',1,'N','Y',0,null,0,'vbfree9','mapub.mapub_acquirepricelog.vbfree9',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,39,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLM',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree6',0,'N',1,'N','Y',0,null,0,'vfree6','mapub.mapub_acquirepricelog.vfree6',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,16,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLN',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvendorid',0,'N',1,'N','Y',0,null,0,'cvendorid','mapub.mapub_acquirepricelog.cvendorid',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,'供应商档案,code=N',null,null,'N',1,8,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLO',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree2',0,'N',1,'N','Y',0,null,0,'vbfree2','mapub.mapub_acquirepricelog.vbfree2',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,32,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLP',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree1',0,'N',1,'N','Y',0,null,0,'vbfree1','mapub.mapub_acquirepricelog.vbfree1',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,31,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree3',0,'N',1,'N','Y',0,null,0,'vbfree3','mapub.mapub_acquirepricelog.vbfree3',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,33,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLR',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialpriceid',0,'N',1,'N','Y',0,null,0,'cmaterialpriceid','mapub.mapub_acquirepricelog.cmaterialpriceid',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,43,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLS',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbmaterialid',0,'N',1,'N','N',0,null,0,'cbmaterialid','mapub.mapub_acquirepricelog.cbmaterialid',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',0,26,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLT',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbprojectid',0,'N',1,'N','Y',0,null,0,'cbprojectid','mapub.mapub_acquirepricelog.cbprojectid',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,'项目,code=N',null,null,'N',1,27,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLU',1,-1,null,null,0,1,null,-1,'N',null,-1,'errorinfo',0,'N',1,'N','Y',0,null,0,'errorinfo','mapub.mapub_acquirepricelog.errorinfo',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,'13810200003',null,'N',1,45,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLV',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree4',0,'N',1,'N','Y',0,null,0,'vfree4','mapub.mapub_acquirepricelog.vfree4',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,14,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLW',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree10',0,'N',1,'N','Y',0,null,0,'vbfree10','mapub.mapub_acquirepricelog.vbfree10',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,40,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLX',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree5',0,'N',1,'N','Y',0,null,0,'vfree5','mapub.mapub_acquirepricelog.vfree5',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,15,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLY',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree2',0,'N',1,'N','Y',0,null,0,'vfree2','mapub.mapub_acquirepricelog.vfree2',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,12,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QLZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccustomerid',0,'N',1,'N','Y',0,null,0,'ccustomerid','mapub.mapub_acquirepricelog.ccustomerid',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,'客户档案,code=N',null,null,'N',1,10,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QM0',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree8',0,'N',1,'N','Y',0,null,0,'vbfree8','mapub.mapub_acquirepricelog.vbfree8',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,38,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QM1',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbproductorid',0,'N',1,'N','Y',0,null,0,'cbproductorid','mapub.mapub_acquirepricelog.cbproductorid',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,'生产厂商(自定义档案),code=N',null,null,'N',1,29,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QM2',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree5',0,'N',1,'N','Y',0,null,0,'vbfree5','mapub.mapub_acquirepricelog.vbfree5',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,35,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QM3',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree1',0,'N',1,'N','Y',0,null,0,'vfree1','mapub.mapub_acquirepricelog.vfree1',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,11,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QM4',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree4',0,'N',1,'N','Y',0,null,0,'vbfree4','mapub.mapub_acquirepricelog.vbfree4',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,34,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QM5',1,-1,null,null,0,1,null,-1,'N',null,-1,'solveplan',0,'N',1,'N','Y',0,null,0,'solveplan','mapub.mapub_acquirepricelog.solveplan',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,46,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QM6',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree3',0,'N',1,'N','Y',0,null,0,'vfree3','mapub.mapub_acquirepricelog.vfree3',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,13,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QM7',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree10',0,'N',1,'N','Y',0,null,0,'vfree10','mapub.mapub_acquirepricelog.vfree10',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,20,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QM8',1,-1,null,null,0,1,null,-1,'N',null,-1,'vfree8',0,'N',1,'N','Y',0,null,0,'vfree8','mapub.mapub_acquirepricelog.vfree8',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,null,null,null,'N',1,18,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QM9',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbvendorid',0,'N',1,'N','Y',0,null,0,'cbvendorid','mapub.mapub_acquirepricelog.cbvendorid',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,'供应商档案,code=N',null,null,'N',1,28,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMB',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprojectid',0,'N',1,'N','Y',0,null,0,'cprojectid','mapub.mapub_acquirepricelog.cprojectid',null,'N',0,null,'1002Z310000000007I2A','@@@@',1,'项目,code=N',null,null,'N',1,6,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000009K5K',1,-1,null,null,0,0,null,-1,'N','cmaterialid',-1,'cmaterialid.code',null,'N',1,'N','Y',0,null,0,'code','uap.material_v.code',null,'N',0,null,'1002Z310000000007I2A',null,1,null,'13810200004',null,'N',1,3,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000009K5L',1,-1,null,null,0,0,null,-1,'N','cmaterialid',-1,'cmaterialid.name',null,'N',1,'N','Y',0,null,0,'name','uap.material_v.name',null,'N',0,null,'1002Z310000000007I2A',null,1,null,'13810200005',null,'N',1,4,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000009K5M',1,-1,null,null,0,0,null,-1,'N','cbmaterialid',-1,'cbmaterialid.name',null,'N',1,'N','Y',0,null,0,'name','uap.material_v.name',null,'N',0,null,'1002Z310000000007I2A',null,1,null,'13810200006',null,'N',1,25,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000009K5N',1,-1,null,null,0,0,null,-1,'N','ccostcenterid',-1,'ccostcenterid.ccname',null,'N',1,'N','Y',0,null,0,'ccname','resa.resacostcenter.ccname',null,'N',0,null,'1002Z310000000007I2A',null,1,null,'13810200007',null,'N',1,1,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000009K5O',1,-1,null,null,0,0,null,-1,'N','cbcostcenterid',-1,'cbcostcenterid.ccname',null,'N',1,'N','Y',0,null,0,'ccname','resa.resacostcenter.ccname',null,'N',0,null,'1002Z310000000007I2A',null,1,null,'13810200008',null,'N',1,22,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000009K5Q',1,-1,null,null,0,0,null,-1,'N','cbmaterialid',-1,'cbmaterialid.code',null,'N',1,'N','Y',0,null,0,'code','uap.material_v.code',null,'N',0,null,'1002Z310000000007I2A',null,1,null,'13810200009',null,'N',1,24,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z31000000000CMI6',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccostcenterid',null,'N',1,'N','Y',0,null,0,'ccostcenterid','mapub.mapub_acquirepricelog.ccostcenterid',null,'N',0,null,'1002Z310000000007I2A',null,1,null,'138102000010',null,'N',1,0,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z31000000000CMI8',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbcostcenterid',null,'N',1,'N','Y',0,null,0,'cbcostcenterid','mapub.mapub_acquirepricelog.cbcostcenterid',null,'N',0,null,'1002Z310000000007I2A',null,1,null,'138102000011',null,'N',1,21,'stdcostprocess_mat','stdcostprocess_mat',0,'2015-05-14 10:36:02','N',null,null,null,1,1,'N',1,null,100)
go

