insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QME',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree4',0,'N',1,'N','Y',10,null,0,'vfree4','mapub.mapub_acquirepricelog.vfree4',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',1,13,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMF',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree2',0,'N',1,'N','Y',8,null,0,'vfree2','mapub.mapub_acquirepricelog.vfree2',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',1,11,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMG',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree3',0,'N',1,'N','Y',9,null,0,'vfree3','mapub.mapub_acquirepricelog.vfree3',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',1,12,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMH',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree1',0,'N',1,'N','Y',7,null,0,'vfree1','mapub.mapub_acquirepricelog.vfree1',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',1,10,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMI',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree7',0,'N',1,'N','Y',13,null,0,'vfree7','mapub.mapub_acquirepricelog.vfree7',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',1,16,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMJ',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree10',0,'N',1,'N','Y',16,null,0,'vfree10','mapub.mapub_acquirepricelog.vfree10',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',1,19,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMK',1,-1,null,null,0,0,null,-1,'N',null,-1,'cactivityid',0,'N',1,'N','N',24,null,0,'cactivityid','mapub.mapub_acquirepricelog.cactivityid',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,'13810210009',null,'N',0,24,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QML',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccostcenterid',0,'N',1,'N','N',18,null,0,'ccostcenterid','mapub.mapub_acquirepricelog.ccostcenterid',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',0,20,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,0,0,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMM',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree5',0,'N',1,'N','Y',11,null,0,'vfree5','mapub.mapub_acquirepricelog.vfree5',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',1,14,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMN',1,-1,null,null,0,0,null,-1,'N',null,-1,'cproductorid',0,'N',1,'N','Y',5,null,0,'cproductorid','mapub.mapub_acquirepricelog.cproductorid',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,'生产厂商(自定义档案),code=N',null,null,'N',1,8,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMO',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree6',0,'N',1,'N','Y',12,null,0,'vfree6','mapub.mapub_acquirepricelog.vfree6',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',1,15,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMP',1,-1,null,null,0,0,null,-1,'N',null,-1,'cmaterialpriceid',0,'N',1,'N','N',29,null,0,'cmaterialpriceid','mapub.mapub_acquirepricelog.cmaterialpriceid',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',0,29,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'cvendorid',0,'N',1,'N','Y',4,null,0,'cvendorid','mapub.mapub_acquirepricelog.cvendorid',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,'供应商档案,code=N',null,null,'N',1,7,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMR',1,-1,null,null,0,0,null,-1,'N',null,-1,'cprojectid',0,'N',1,'N','Y',2,null,0,'cprojectid','mapub.mapub_acquirepricelog.cprojectid',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,'项目,code=N',null,null,'N',1,6,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMS',1,-1,null,null,0,0,null,-1,'N',null,-1,'isourcetype',0,'N',1,'N','N',28,null,0,'isourcetype','mapub.mapub_acquirepricelog.isourcetype',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',0,28,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMT',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree8',0,'N',1,'N','Y',14,null,0,'vfree8','mapub.mapub_acquirepricelog.vfree8',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',1,17,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMU',1,-1,null,null,0,0,null,-1,'N',null,-1,'errorinfo',0,'N',1,'N','Y',30,null,0,'errorinfo','mapub.mapub_acquirepricelog.errorinfo',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,'13810210011',null,'N',1,30,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMV',1,-1,null,null,0,0,null,-1,'N',null,-1,'ccustomerid',0,'N',1,'N','Y',6,null,0,'ccustomerid','mapub.mapub_acquirepricelog.ccustomerid',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,'客户档案,code=N',null,null,'N',1,9,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMW',1,-1,null,null,0,0,null,-1,'N',null,-1,'prioritylevel',0,'N',1,'N','N',27,null,0,'prioritylevel','mapub.mapub_acquirepricelog.prioritylevel',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',0,27,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMX',1,-1,null,null,0,0,null,-1,'N',null,-1,'cmaterialid',0,'N',1,'N','N',3,null,0,'cmaterialid','mapub.mapub_acquirepricelog.cmaterialid',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',0,5,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,0,0,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMY',1,-1,null,null,0,0,null,-1,'N',null,-1,'celementid',0,'N',1,'N','N',21,null,0,'celementid','mapub.mapub_acquirepricelog.celementid',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,'核算要素(财务组织),code=N','13810210010',null,'N',0,21,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QMZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'finstoragetype',0,'N',1,'N','Y',17,null,0,'finstoragetype','mapub.mapub_acquirepricelog.finstoragetype',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',1,4,'stdcostprocess_cost','入库类型',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QN0',1,-1,null,null,0,0,null,-1,'N',null,-1,'vfree9',0,'N',1,'N','Y',15,null,0,'vfree9','mapub.mapub_acquirepricelog.vfree9',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',1,18,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000007QN1',1,-1,null,null,0,0,null,-1,'N',null,-1,'solveplan',0,'N',1,'N','Y',31,null,0,'solveplan','mapub.mapub_acquirepricelog.solveplan',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',1,31,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000009K9F',1,-1,null,null,0,0,null,-1,'N','ccostcenterid',-1,'ccostcenterid.ccname',0,'N',1,'N','Y',20,null,0,'ccname','resa.resacostcenter.ccname',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,'13810210002',null,'N',1,1,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000009K9G',1,-1,null,null,0,0,null,-1,'N','ccostcenterid',-1,'ccostcenterid.cccode',0,'N',1,'N','Y',19,null,0,'cccode','resa.resacostcenter.cccode',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,'13810210003',null,'N',1,0,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000009K9H',1,-1,null,null,0,0,null,-1,'N','cmaterialid',-1,'cmaterialid.name',0,'N',1,'N','Y',1,null,0,'name','uap.material_v.name',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,'13810210004',null,'N',1,3,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000009K9I',1,-1,null,null,0,0,null,-1,'N','cmaterialid',-1,'cmaterialid.code',0,'N',1,'N','Y',0,null,0,'code','uap.material_v.code',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,'13810210005',null,'N',1,2,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1011Z310000000004KCR',1,-1,null,null,0,0,null,-1,'N','cactivityid',-1,'cactivityid.vactivitycode',0,'N',1,'N','Y',25,null,0,'vactivitycode','mmbd.bd_activity.vactivitycode',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',1,25,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1011Z310000000004KCS',1,-1,null,null,0,0,null,-1,'N','cactivityid',-1,'cactivityid.vactivityname',0,'N',1,'N','Y',26,null,0,'vactivityname','mmbd.bd_activity.vactivityname',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,null,null,'N',1,26,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1011Z310000000004KCT',1,-1,null,null,0,0,null,-1,'N','celementid',-1,'celementid.factorname',0,'N',1,'N','Y',23,null,0,'factorname','resa.FactorAsoa.factorname',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,'13810210007',null,'N',1,23,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1011Z310000000004KCU',1,-1,null,null,0,0,null,-1,'N','celementid',-1,'celementid.factorcode',0,'N',1,'N','Y',22,null,0,'factorcode','resa.FactorAsoa.factorcode',null,'N',0,null,'1002Z310000000007QMD','@@@@',1,null,'13810210008',null,'N',1,22,'stdcostprocess_cost','stdcostprocess_cost',0,'2015-05-13 08:54:40','N',null,null,null,1,1,'N',1,null,100)
go

