insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZI',1,-1,null,null,0,1,null,-1,'N',null,-1,'vpricesource',0,'N',1,'N','Y',0,null,0,'vpricesource','mapub.mapub_materialPriceSources_b.vpricesource',null,'N',0,null,'1002Z310000000010VZH','@@@@',1,null,null,null,'N',1,3,'itempks','物料价格来源明细',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,200)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','Y',0,null,0,'pk_org','mapub.mapub_materialPriceSources_b.pk_org','corgcode=code','N',0,null,'1002Z310000000010VZH','@@@@',1,null,null,null,'N',1,4,'itempks','物料价格来源明细',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,200)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZK',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',0,null,0,'ts','mapub.mapub_materialPriceSources_b.ts',null,'N',0,null,'1002Z310000000010VZH','@@@@',1,null,null,null,'N',0,6,'itempks','物料价格来源明细',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZL',1,-1,null,null,0,1,null,-1,'N',null,-1,'corgcode',0,'N',1,'N','N',0,null,0,'corgcode','mapub.mapub_materialPriceSources_b.corgcode',null,'N',0,null,'1002Z310000000010VZH','@@@@',1,null,null,null,'N',0,5,'itempks','物料价格来源明细',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZM',1,-1,null,null,0,1,null,-1,'N',null,-1,'cpricesourcesid',0,'N',1,'N','N',0,null,0,'cpricesourcesid','mapub.mapub_materialPriceSources_b.cpricesourcesid',null,'N',0,null,'1002Z310000000010VZH','@@@@',1,null,null,null,'N',0,2,'itempks','物料价格来源明细',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZN',1,-1,null,null,0,1,null,-1,'N',null,-1,'cpricesources_bid',0,'N',1,'N','N',0,null,0,'cpricesources_bid','mapub.mapub_materialPriceSources_b.cpricesources_bid',null,'N',0,null,'1002Z310000000010VZH','@@@@',1,null,null,null,'N',0,1,'itempks','物料价格来源明细',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

