/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mapub.materialpricebase.enumeration;

import nc.md.model.IEnumValue;
import nc.md.model.impl.MDEnum;

/**
 * 价格来源枚举值
 * 
 * @since 6.36
 * @version 2014-11-25 下午2:55:49
 * @author zhangchd
 */
public class PriceSourceEnum extends MDEnum {
    public PriceSourceEnum(IEnumValue enumvalue) {
        super(enumvalue);
    }

    /**
     * 手工录入
     */
    public static final PriceSourceEnum MANUAL = MDEnum.valueOf(PriceSourceEnum.class, Integer.valueOf(1));

    /**
     * 计划价
     */
    public static final PriceSourceEnum PLAN = MDEnum.valueOf(PriceSourceEnum.class, Integer.valueOf(2));

    /**
     * 参考成本
     */
    public static final PriceSourceEnum REFERENCE = MDEnum.valueOf(PriceSourceEnum.class, Integer.valueOf(3));

    /**
     * 平均采购入库单价
     */
    public static final PriceSourceEnum PINGJUNCAIGOURUKU = MDEnum.valueOf(PriceSourceEnum.class, Integer.valueOf(13));

    /**
     * 最新结存价
     */
    public static final PriceSourceEnum FORWARD = MDEnum.valueOf(PriceSourceEnum.class, Integer.valueOf(6));

    /**
     * 标准成本
     */
    public static final PriceSourceEnum STDCOST = MDEnum.valueOf(PriceSourceEnum.class, Integer.valueOf(9));

}
