/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mapub.materialpricebase.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * 材料价格库
 * 表头VO
 * 
 * @since 6.36
 * @version 2014-11-6 上午10:27:46
 * @author zhangchd
 */
@SuppressWarnings("serial")
public class MaterialPriceBaseHeadVO extends SuperVO {

    public static final String CMATERIALPRICEID = "cmaterialpriceid";

    public static final String PK_GROUP = "pk_group";

    public static final String PK_ORG = "pk_org";

    public static final String PK_ORG_V = "pk_org_v";

    public static final String VPRICECODE = "vpricecode";

    public static final String VPRICENAME = "vpricename";

    public static final String CCRRENCYID = "ccrrencyid";

    public static final String VPRICESOURCE = "vpricesource";

    public static final String VPRICESOURCENUM = "vpricesourcenum";

    public static final String DBEGINDATE = "dbegindate";

    public static final String DENDDATE = "denddate";

    public static final String VNOTE = "vnote";

    public static final String BLOCKINGFLAG = "blockingflag";

    public static final String CREATOR = "creator";

    public static final String CREATIONTIME = "creationtime";

    public static final String MODIFIER = "modifier";

    public static final String MODIFIEDTIME = "modifiedtime";

    /**
     * 属性cmaterialpriceid的Getter方法.属性名：材料价格库
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCmaterialpriceid() {
        return (java.lang.String) this.getAttributeValue("cmaterialpriceid");
    }

    /**
     * 属性cmaterialpricebaseid的Setter方法.属性名：材料价格库
     * 创建日期:
     * 
     * @param newCmaterialpriceid java.lang.String
     */
    public void setCmaterialpriceid(java.lang.String newCmaterialpriceid) {
        this.setAttributeValue("cmaterialpriceid", newCmaterialpriceid);
    }

    /**
     * 属性pk_group的Getter方法.属性名：集团
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_group() {
        return (java.lang.String) this.getAttributeValue("pk_group");
    }

    /**
     * 属性pk_group的Setter方法.属性名：集团
     * 创建日期:
     * 
     * @param newPk_group java.lang.String
     */
    public void setPk_group(java.lang.String newPk_group) {
        this.setAttributeValue("pk_group", newPk_group);
    }

    /**
     * 属性pk_org的Getter方法.属性名：工厂
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org() {
        return (java.lang.String) this.getAttributeValue("pk_org");
    }

    /**
     * 属性pk_org的Setter方法.属性名：工厂
     * 创建日期:
     * 
     * @param newPk_org java.lang.String
     */
    public void setPk_org(java.lang.String newPk_org) {
        this.setAttributeValue("pk_org", newPk_org);
    }

    /**
     * 属性pk_org_v的Getter方法.属性名：工厂版本
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org_v() {
        return (java.lang.String) this.getAttributeValue("pk_org_v");
    }

    /**
     * 属性pk_org_v的Setter方法.属性名：工厂版本
     * 创建日期:
     * 
     * @param newPk_org_v java.lang.String
     */
    public void setPk_org_v(java.lang.String newPk_org_v) {
        this.setAttributeValue("pk_org_v", newPk_org_v);
    }

    /**
     * 属性vpricecode的Getter方法.属性名：价格库编码
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVpricecode() {
        return (java.lang.String) this.getAttributeValue("vpricecode");
    }

    /**
     * 属性vpricecode的Setter方法.属性名：价格库编码
     * 创建日期:
     * 
     * @param newVpricecode java.lang.String
     */
    public void setVpricecode(java.lang.String newVpricecode) {
        this.setAttributeValue("vpricecode", newVpricecode);
    }

    /**
     * 属性vpricename的Getter方法.属性名：价格库名称
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVpricename() {
        return (java.lang.String) this.getAttributeValue("vpricename");
    }

    /**
     * 属性vpricename的Setter方法.属性名：价格库名称
     * 创建日期:
     * 
     * @param newVpricename java.lang.String
     */
    public void setVpricename(java.lang.String newVpricename) {
        this.setAttributeValue("vpricename", newVpricename);
    }

    /**
     * 属性ccrrencyid的Getter方法.属性名：币种
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCcrrencyid() {
        return (java.lang.String) this.getAttributeValue("ccrrencyid");
    }

    /**
     * 属性ccrrencyid的Setter方法.属性名：币种
     * 创建日期:
     * 
     * @param newCcrrencyid java.lang.String
     */
    public void setCcrrencyid(java.lang.String newCcrrencyid) {
        this.setAttributeValue("ccrrencyid", newCcrrencyid);
    }

    /**
     * 属性vpricesource的Getter方法.属性名：价格来源
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVpricesource() {
        return (java.lang.String) this.getAttributeValue("vpricesource");
    }

    /**
     * 属性vpricesource的Setter方法.属性名：价格来源
     * 创建日期:
     * 
     * @param newVpricesource java.lang.String
     */
    public void setVpricesource(java.lang.String newVpricesource) {
        this.setAttributeValue("vpricesource", newVpricesource);
    }

    /**
     * 属性vpricesourcenum的Getter方法.属性名：价格来源数
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVpricesourcenum() {
        return (java.lang.String) this.getAttributeValue("vpricesourcenum");
    }

    /**
     * 属性vpricesourcenum的Setter方法.属性名：价格来源数
     * 创建日期:
     * 
     * @param newVpricesourcenum java.lang.String
     */
    public void setVpricesourcenum(java.lang.String newVpricesourcenum) {
        this.setAttributeValue("vpricesourcenum", newVpricesourcenum);
    }

    /**
     * 属性dbegindate的Getter方法.属性名：生效日期
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDate
     */
    public nc.vo.pub.lang.UFDate getDbegindate() {
        return (nc.vo.pub.lang.UFDate) this.getAttributeValue("dbegindate");
    }

    /**
     * 属性dbegindate的Setter方法.属性名：生效日期
     * 创建日期:
     * 
     * @param newDbegindate nc.vo.pub.lang.UFDate
     */
    public void setDbegindate(nc.vo.pub.lang.UFDate newDbegindate) {
        this.setAttributeValue("dbegindate", newDbegindate);
    }

    /**
     * 属性denddate的Getter方法.属性名：失效日期
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDate
     */
    public nc.vo.pub.lang.UFDate getDenddate() {
        return (nc.vo.pub.lang.UFDate) this.getAttributeValue("denddate");
    }

    /**
     * 属性denddate的Setter方法.属性名：失效日期
     * 创建日期:
     * 
     * @param newDenddate nc.vo.pub.lang.UFDate
     */
    public void setDenddate(nc.vo.pub.lang.UFDate newDenddate) {
        this.setAttributeValue("denddate", newDenddate);
    }

    /**
     * 属性vnote的Getter方法.属性名：备注
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVnote() {
        return (java.lang.String) this.getAttributeValue("vnote");
    }

    /**
     * 属性vnote的Setter方法.属性名：备注
     * 创建日期:
     * 
     * @param newVnote java.lang.String
     */
    public void setVnote(java.lang.String newVnote) {
        this.setAttributeValue("vnote", newVnote);
    }

    /**
     * 属性blockingflag的Getter方法.属性名：锁定
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getBlockingflag() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("blockingflag");
    }

    /**
     * 属性blockingflag的Setter方法.属性名：锁定
     * 创建日期:
     * 
     * @param newBlockingflag nc.vo.pub.lang.UFBoolean
     */
    public void setBlockingflag(nc.vo.pub.lang.UFBoolean newBlockingflag) {
        this.setAttributeValue("blockingflag", newBlockingflag);
    }

    /**
     * 属性creator的Getter方法.属性名：创建人
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCreator() {
        return (java.lang.String) this.getAttributeValue("creator");
    }

    /**
     * 属性creator的Setter方法.属性名：创建人
     * 创建日期:
     * 
     * @param newCreator java.lang.String
     */
    public void setCreator(java.lang.String newCreator) {
        this.setAttributeValue("creator", newCreator);
    }

    /**
     * 属性creationtime的Getter方法.属性名：创建时间
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getCreationtime() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("creationtime");
    }

    /**
     * 属性creationtime的Setter方法.属性名：创建时间
     * 创建日期:
     * 
     * @param newCreationtime nc.vo.pub.lang.UFDateTime
     */
    public void setCreationtime(nc.vo.pub.lang.UFDateTime newCreationtime) {
        this.setAttributeValue("creationtime", newCreationtime);
    }

    /**
     * 属性modifier的Getter方法.属性名：最后修改人
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getModifier() {
        return (java.lang.String) this.getAttributeValue("modifier");
    }

    /**
     * 属性modifier的Setter方法.属性名：最后修改人
     * 创建日期:
     * 
     * @param newModifier java.lang.String
     */
    public void setModifier(java.lang.String newModifier) {
        this.setAttributeValue("modifier", newModifier);
    }

    /**
     * 属性modifiedtime的Getter方法.属性名：最后修改时间
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getModifiedtime() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("modifiedtime");
    }

    /**
     * 属性modifiedtime的Setter方法.属性名：最后修改时间
     * 创建日期:
     * 
     * @param newModifiedtime nc.vo.pub.lang.UFDateTime
     */
    public void setModifiedtime(nc.vo.pub.lang.UFDateTime newModifiedtime) {
        this.setAttributeValue("modifiedtime", newModifiedtime);
    }

    /**
     * 属性dr的Getter方法.属性名：dr
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getDr() {
        return (java.lang.Integer) this.getAttributeValue("dr");
    }

    /**
     * 属性dr的Setter方法.属性名：dr
     * 创建日期:
     * 
     * @param newDr java.lang.Integer
     */
    public void setDr(java.lang.Integer newDr) {
        this.setAttributeValue("dr", newDr);
    }

    /**
     * 属性ts的Getter方法.属性名：ts
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getTs() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("ts");
    }

    /**
     * 属性ts的Setter方法.属性名：ts
     * 创建日期:
     * 
     * @param newTs nc.vo.pub.lang.UFDateTime
     */
    public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
        this.setAttributeValue("ts", newTs);
    }

    /**
     * <p>
     * 取得父VO主键字段.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getParentPKFieldName() {
        return null;
    }

    /**
     * <p>
     * 取得表主键.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getPKFieldName() {
        return "cmaterialpriceid";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getTableName() {
        return "mapub_materialpricebase";
    }

    public static java.lang.String getDefaultTableName() {
        return "mapub_materialpricebase";
    }

    /**
     * 按照默认方式创建构造子.
     * 创建日期:
     */
    public MaterialPriceBaseHeadVO() {
        super();
    }

    @Override
    @nc.vo.annotation.MDEntityInfo(beanFullclassName = "nc.vo.mapub.materialpricebase.entity.MaterialPriceBaseHeadVO")
    public IVOMeta getMetaData() {
        IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("mapub.mapub_materialpricebase");
        return meta;
    }
}
