/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mapub.materialpricebase.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 价格来源对话框 </b>
 * <p>
 * headVO
 * </p>
 * 创建日期:
 *
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class MaterialPriceSourcesHeadVO extends SuperVO {

    private java.lang.String cpricesourcesid;

    private Integer dr = 0;

    private UFDateTime ts;

    public java.lang.String getCpricesourcesid() {
        return this.cpricesourcesid;
    }

    public void setCpricesourcesid(java.lang.String cpricesourcesid) {
        this.cpricesourcesid = cpricesourcesid;
    }

    /**
     * 属性dr的Getter方法.属性名：dr
     * 创建日期:
     *
     * @return java.lang.Integer
     */
    public java.lang.Integer getDr() {
        return this.dr;
    }

    /**
     * 属性dr的Setter方法.属性名：dr
     * 创建日期:
     *
     * @param newDr java.lang.Integer
     */
    public void setDr(java.lang.Integer newDr) {
        this.dr = newDr;
    }

    /**
     * 属性ts的Getter方法.属性名：ts
     * 创建日期:
     *
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getTs() {
        return this.ts;
    }

    /**
     * 属性ts的Setter方法.属性名：ts
     * 创建日期:
     *
     * @param newTs nc.vo.pub.lang.UFDateTime
     */
    public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
        this.ts = newTs;
    }

    /**
     * <p>
     * 取得父VO主键字段.
     * <p>
     * 创建日期:
     *
     * @return java.lang.String
     */
    @Override
    public java.lang.String getParentPKFieldName() {
        return null;
    }

    /**
     * <p>
     * 取得表主键.
     * <p>
     * 创建日期:
     *
     * @return java.lang.String
     */
    @Override
    public java.lang.String getPKFieldName() {
        return "cpricesourcesid";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     *
     * @return java.lang.String
     */
    @Override
    public java.lang.String getTableName() {
        return "mapub_materialpricesources";
    }

    /**
     * 按照默认方式创建构造子.
     * 创建日期:
     */
    public MaterialPriceSourcesHeadVO() {
        super();
    }

    @Override
    public IVOMeta getMetaData() {
        IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("mapub.mapub_materialPriceSources");
        return meta;
    }
}
