/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mapub.materialpricebase.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 取价对话框 </b>
 * <p>
 * bodyVO
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class MaterialPullPriceBodyVO extends SuperVO {

    public static final String CMATERIALPULLPRICE_BID = "cmaterialpullprice_bid";

    public static final String CMATERIALPULLPRICEID = "cmaterialpullpriceid";

    /**
     * 属性cmaterialpullprice_bid的Getter方法.属性名：物料取价明细
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCmaterialpullprice_bid() {
        return (java.lang.String) this.getAttributeValue("cmaterialpullprice_bid");
    }

    /**
     * 属性cmaterialpullprice_bid的Setter方法.属性名：物料取价明细
     * 创建日期:
     * 
     * @param newCmaterialpullprice_bid java.lang.String
     */
    public void setCmaterialpullprice_bid(java.lang.String newCmaterialpullprice_bid) {
        this.setAttributeValue("cmaterialpullprice_bid", newCmaterialpullprice_bid);
    }

    /**
     * 属性cmaterialpullpriceid的Getter方法.属性名：物料取价
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCmaterialpullpriceid() {
        return (java.lang.String) this.getAttributeValue("cmaterialpullpriceid");
    }

    /**
     * 属性cmaterialpullpriceid的Setter方法.属性名：物料取价
     * 创建日期:
     * 
     * @param newCmaterialpullpriceid java.lang.String
     */
    public void setCmaterialpullpriceid(java.lang.String newCmaterialpullpriceid) {
        this.setAttributeValue("cmaterialpullpriceid", newCmaterialpullpriceid);
    }

    /**
     * 属性dr的Getter方法.属性名：dr
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getDr() {
        return (java.lang.Integer) this.getAttributeValue("dr");
    }

    /**
     * 属性dr的Setter方法.属性名：dr
     * 创建日期:
     * 
     * @param newDr java.lang.Integer
     */
    public void setDr(java.lang.Integer newDr) {
        this.setAttributeValue("dr", newDr);
    }

    /**
     * 属性ts的Getter方法.属性名：ts
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getTs() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("ts");
    }

    /**
     * 属性ts的Setter方法.属性名：ts
     * 创建日期:
     * 
     * @param newTs nc.vo.pub.lang.UFDateTime
     */
    public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
        this.setAttributeValue("ts", newTs);
    }

    /**
     * <p>
     * 取得父VO主键字段.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getParentPKFieldName() {
        return "cmaterialpullpriceid";
    }

    /**
     * <p>
     * 取得表主键.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getPKFieldName() {
        return "cmaterialpullprice_bid";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getTableName() {
        return "mapub_materialpullprice_b";
    }

    /**
     * 按照默认方式创建构造子.
     * 创建日期:
     */
    public MaterialPullPriceBodyVO() {
        super();
    }

    @Override
    @nc.vo.annotation.MDEntityInfo(beanFullclassName = "nc.vo.mapub.materialpricebase.entity.MaterialPullPriceBodyVO")
    public IVOMeta getMetaData() {
        IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("mapub.mapub_materialpullprice_b");
        return meta;
    }
}
