/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mapub.materialpricebase.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 价格来源对话框 </b>
 * <p>
 * bodyVO
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class MaterialPriceSourcesBodyVO extends SuperVO {
    private transient java.lang.String cpricesourcesid;

    public static final String CPRICESOURCESID = "cpricesourcesid";

    public static final String CPRICESOURCES_BID = "cpricesources_bid";

    public static final String VPRICESOURCE = "vpricesource";

    public static final String PK_ORG = "pk_org";

    public static final String CORGCODE = "corgcode";

    public static final String CTOTALCODE = "ctotalcode";

    /**
     * 属性cpricesources_bid的Getter方法.属性名：物料价格来源明细
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCpricesources_bid() {
        return (java.lang.String) this.getAttributeValue("cpricesources_bid");
    }

    /**
     * 属性cpricesources_bid的Setter方法.属性名：物料价格来源明细
     * 创建日期:
     * 
     * @param newCpricesources_bid java.lang.String
     */
    public void setCpricesources_bid(java.lang.String newCpricesources_bid) {
        this.setAttributeValue("cpricesources_bid", newCpricesources_bid);
    }

    /**
     * 属性cpricesourcesid的Getter方法.属性名：物料价格来源
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCpricesourcesid() {
        return this.cpricesourcesid;
    }

    /**
     * 属性cpricesourcesid的Setter方法.属性名：物料价格来源
     * 创建日期:
     * 
     * @param newCpricesourcesid java.lang.String
     */
    public void setCpricesourcesid(java.lang.String newCpricesourcesid) {
        this.cpricesourcesid = newCpricesourcesid;
    }

    /**
     * 属性vpricesource的Getter方法.属性名：价格来源
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getVpricesource() {
        return (java.lang.Integer) this.getAttributeValue("vpricesource");
    }

    /**
     * 属性vpricesource的Setter方法.属性名：价格来源
     * 创建日期:
     * 
     * @param newVpricesource java.lang.Integer
     */
    public void setVpricesource(java.lang.Integer newVpricesource) {
        this.setAttributeValue("vpricesource", newVpricesource);
    }

    /**
     * 属性pk_org的Getter方法.属性名：业务单元
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org() {
        return (java.lang.String) this.getAttributeValue("pk_org");
    }

    /**
     * 属性pk_org的Setter方法.属性名：业务单元
     * 创建日期:
     * 
     * @param newPk_org java.lang.String
     */
    public void setPk_org(java.lang.String newPk_org) {
        this.setAttributeValue("pk_org", newPk_org);
    }

    /**
     * 属性corgcode的Getter方法.属性名：业务单元编码
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCorgcode() {
        return (java.lang.String) this.getAttributeValue("corgcode");
    }

    /**
     * 属性corgcode的Setter方法.属性名：业务单元编码
     * 创建日期:
     * 
     * @param newCorgcode java.lang.String
     */
    public void setCorgcode(java.lang.String newCorgcode) {
        this.setAttributeValue("corgcode", newCorgcode);
    }

    /**
     * 属性ctotalcode的Getter方法.属性名：行编码
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCtotalcode() {
        return (java.lang.String) this.getAttributeValue("ctotalcode");
    }

    /**
     * 属性ctotalcode的Setter方法.属性名：行编码
     * 创建日期:
     * 
     * @param newCtotalcode java.lang.String
     */
    public void setCtotalcode(java.lang.String newCtotalcode) {
        this.setAttributeValue("ctotalcode", newCtotalcode);
    }

    /**
     * 属性dr的Getter方法.属性名：dr
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getDr() {
        return (java.lang.Integer) this.getAttributeValue("dr");
    }

    /**
     * 属性dr的Setter方法.属性名：dr
     * 创建日期:
     * 
     * @param newDr java.lang.Integer
     */
    public void setDr(java.lang.Integer newDr) {
        this.setAttributeValue("dr", newDr);
    }

    /**
     * 属性ts的Getter方法.属性名：ts
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getTs() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("ts");
    }

    /**
     * 属性ts的Setter方法.属性名：ts
     * 创建日期:
     * 
     * @param newTs nc.vo.pub.lang.UFDateTime
     */
    public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
        this.setAttributeValue("ts", newTs);
    }

    /**
     * <p>
     * 取得父VO主键字段.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getParentPKFieldName() {
        return "cpricesourcesid";
    }

    /**
     * <p>
     * 取得表主键.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getPKFieldName() {
        return "cpricesources_bid";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getTableName() {
        return "mapub_materialpricesources_b";
    }

    /**
     * 按照默认方式创建构造子.
     * 创建日期:
     */
    public MaterialPriceSourcesBodyVO() {
        super();
    }

    @Override
    @nc.vo.annotation.MDEntityInfo(beanFullclassName = "nc.vo.mapub.materialpricebase.entity.MaterialPriceSourcesBodyVO")
    public IVOMeta getMetaData() {
        IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("mapub.mapub_materialPriceSources_b");
        return meta;
    }
}
