/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mapub.materialpricebase.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 取价对话框 </b>
 * <p>
 * headVO
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class MaterialPullPriceHeadVO extends SuperVO {

    public static final String CMATERIALPULLPRICEID = "cmaterialpullpriceid";

    public static final String CPERIODSCHEME = "cperiodscheme";

    public static final String COSTTYPE = "costtype";

    public static final String CPERIOD = "cperiod";

    public static final String CBEGINDATE = "cbegindate";

    public static final String CENDDATE = "cenddate";

    public static final String PK_GROUP = "pk_group";

    public static final String PK_ORG = "pk_org";

    /**
     * 属性cmaterialpullpriceid的Getter方法.属性名：物料取价
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCmaterialpullpriceid() {
        return (java.lang.String) this.getAttributeValue("cmaterialpullpriceid");
    }

    /**
     * 属性cmaterialpullpriceid的Setter方法.属性名：物料取价
     * 创建日期:
     * 
     * @param newCmaterialpullpriceid java.lang.String
     */
    public void setCmaterialpullpriceid(java.lang.String newCmaterialpullpriceid) {
        this.setAttributeValue("cmaterialpullpriceid", newCmaterialpullpriceid);
    }

    /**
     * 属性cperiod的Getter方法.属性名：会计期间方案
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCperiodscheme() {
        return (java.lang.String) this.getAttributeValue("cperiodscheme");
    }

    /**
     * 属性cperiod的Setter方法.属性名：会计期间方案
     * 创建日期:
     * 
     * @param newCperiodscheme java.lang.String
     */
    public void setCperiodscheme(java.lang.String newCperiodscheme) {
        this.setAttributeValue("cperiodscheme", newCperiodscheme);
    }

    /**
     * 属性costtype的Getter方法.属性名：成本类型
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCosttype() {
        return (java.lang.String) this.getAttributeValue("costtype");
    }

    /**
     * 属性costtype的Setter方法.属性名：成本类型
     * 创建日期:
     * 
     * @param newCosttype java.lang.String
     */
    public void setCosttype(java.lang.String newCosttype) {
        this.setAttributeValue("costtype", newCosttype);
    }

    /**
     * 属性cperiod的Getter方法.属性名：最新结存价会计期间
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCperiod() {
        return (java.lang.String) this.getAttributeValue("cperiod");
    }

    /**
     * 属性cperiod的Setter方法.属性名：最新结存价会计期间
     * 创建日期:
     * 
     * @param newCperiod java.lang.String
     */
    public void setCperiod1(java.lang.String newCperiod) {
        this.setAttributeValue("cperiod", newCperiod);
    }

    /**
     * 属性cbegindate的Getter方法.属性名：平均采购入库开始期间
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCbegindate() {
        return (java.lang.String) this.getAttributeValue("cbegindate");
    }

    /**
     * 属性cbegindate的Setter方法.属性名：平均采购入库开始期间
     * 创建日期:
     * 
     * @param newCbegindate java.lang.String
     */
    public void setCbegindate(java.lang.String newCbegindate) {
        this.setAttributeValue("cbegindate", newCbegindate);
    }

    /**
     * 属性cenddate的Getter方法.属性名：平均采购入库截止期间
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCenddate() {
        return (java.lang.String) this.getAttributeValue("cenddate");
    }

    /**
     * 属性cenddate的Setter方法.属性名：平均采购入库截止期间
     * 创建日期:
     * 
     * @param newCenddate java.lang.String
     */
    public void setCenddate(java.lang.String newCenddate) {
        this.setAttributeValue("cenddate", newCenddate);
    }

    /**
     * 属性pk_group的Getter方法.属性名：集团
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_group() {
        return (java.lang.String) this.getAttributeValue("pk_group");
    }

    /**
     * 属性pk_group的Setter方法.属性名：集团
     * 创建日期:
     * 
     * @param newPk_group java.lang.String
     */
    public void setPk_group(java.lang.String newPk_group) {
        this.setAttributeValue("pk_group", newPk_group);
    }

    /**
     * 属性pk_org的Getter方法.属性名：工厂
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org() {
        return (java.lang.String) this.getAttributeValue("pk_org");
    }

    /**
     * 属性pk_org的Setter方法.属性名：工厂
     * 创建日期:
     * 
     * @param newPk_org java.lang.String
     */
    public void setPk_org(java.lang.String newPk_org) {
        this.setAttributeValue("pk_org", newPk_org);
    }

    /**
     * 属性dr的Getter方法.属性名：dr
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getDr() {
        return (java.lang.Integer) this.getAttributeValue("dr");
    }

    /**
     * 属性dr的Setter方法.属性名：dr
     * 创建日期:
     * 
     * @param newDr java.lang.Integer
     */
    public void setDr(java.lang.Integer newDr) {
        this.setAttributeValue("dr", newDr);
    }

    /**
     * 属性ts的Getter方法.属性名：ts
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getTs() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("ts");
    }

    /**
     * 属性ts的Setter方法.属性名：ts
     * 创建日期:
     * 
     * @param newTs nc.vo.pub.lang.UFDateTime
     */
    public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
        this.setAttributeValue("ts", newTs);
    }

    /**
     * <p>
     * 取得父VO主键字段.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getParentPKFieldName() {
        return null;
    }

    /**
     * <p>
     * 取得表主键.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getPKFieldName() {
        return "cmaterialpullpriceid";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getTableName() {
        return "mapub_materialpullprice";
    }

    /**
     * 按照默认方式创建构造子.
     * 创建日期:
     */
    public MaterialPullPriceHeadVO() {
        super();
    }

    @Override
    @nc.vo.annotation.MDEntityInfo(beanFullclassName = "nc.vo.mapub.materialpricebase.entity.MaterialPullPriceHeadVO")
    public IVOMeta getMetaData() {
        IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("mapub.mapub_materialpullprice");
        return meta;
    }
}
