/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mapub.costpricebase.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 费用价格库明细VO </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 *
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CostPriceBodyVO extends SuperVO {

    public static String CCOSTPRICE_BID = "ccostprice_bid";// 费用价格库明细

    public static String CCOSTPRICEID = "ccostpriceid"; // 费用价格库

    public static String PK_GROUP = "pk_group";

    public static String PK_ORG = "pk_org";

    public static String PK_ORG_V = "pk_org_v";

    public static String CELEMENTID = "celementid";// 核算要素编码

    public static String DPRICE = "dprice";// 金额

    public static String VBFREE1 = "vbfree1";

    public static String VBFREE2 = "vbfree2";

    public static String VBFREE3 = "vbfree3";

    public static String VBFREE4 = "vbfree4";

    /**
     * 获得 ccostpriceBid 的属性值
     *
     * @return the ccostpriceBid
     * @since 2017年7月18日
     * @author
     */
    public String getCcostpriceBid() {
        return (String) this.getAttributeValue("ccostprice_bid");
    }

    /**
     * 设置 ccostpriceBid 的属性值
     *
     * @param ccostpriceBid the ccostpriceBid to set
     * @since 2017年7月18日
     * @author
     */
    public void setCcostpriceBid(String ccostpriceBid) {
        this.setAttributeValue("ccostprice_bid", ccostpriceBid);
    }

    /**
     * 获得 ccostpriceid 的属性值
     *
     * @return the ccostpriceid
     * @since 2017年7月18日
     * @author
     */
    public String getCcostpriceid() {
        return (String) this.getAttributeValue("ccostpriceid");
    }

    /**
     * 设置 ccostpriceid 的属性值
     *
     * @param ccostpriceid the ccostpriceid to set
     * @since 2017年7月18日
     * @author
     */
    public void setCcostpriceid(String ccostpriceid) {
        this.setAttributeValue("ccostpriceid", ccostpriceid);
    }

    /**
     * 获得 pkGroup 的属性值
     *
     * @return the pkGroup
     * @since 2017年7月18日
     * @author
     */
    public String getPkGroup() {
        return (String) this.getAttributeValue("pk_group");
    }

    /**
     * 设置 pkGroup 的属性值
     *
     * @param pkGroup the pkGroup to set
     * @since 2017年7月18日
     * @author
     */
    public void setPkGroup(String pkGroup) {
        this.setAttributeValue("pk_group", pkGroup);
    }

    /**
     * 获得 pkOrg 的属性值
     *
     * @return the pkOrg
     * @since 2017年7月18日
     * @author
     */
    public String getPkOrg() {
        return (String) this.getAttributeValue("pk_org");
    }

    /**
     * 设置 pkOrg 的属性值
     *
     * @param pkOrg the pkOrg to set
     * @since 2017年7月18日
     * @author
     */
    public void setPkOrg(String pkOrg) {
        this.setAttributeValue("pk_org", pkOrg);
    }

    /**
     * 获得 pkOrgV 的属性值
     *
     * @return the pkOrgV
     * @since 2017年7月18日
     * @author
     */
    public String getPkOrgV() {
        return (String) this.getAttributeValue("pk_org_v");
    }

    /**
     * 设置 pkOrgV 的属性值
     *
     * @param pkOrgV the pkOrgV to set
     * @since 2017年7月18日
     * @author
     */
    public void setPkOrgV(String pkOrgV) {
        this.setAttributeValue("pk_org_v", pkOrgV);
    }

    /**
     * 获得 celementid 的属性值
     *
     * @return the celementid
     * @since 2017年7月18日
     * @author
     */
    public String getCelementid() {
        return (String) this.getAttributeValue("celementid");
    }

    /**
     * 设置 celementid 的属性值
     *
     * @param celementid the celementid to set
     * @since 2017年7月18日
     * @author
     */
    public void setCelementid(String celementid) {
        this.setAttributeValue("celementid", celementid);
    }

    /**
     * 获得 dprice 的属性值
     *
     * @return the dprice
     * @since 2017年7月18日
     * @author
     */
    public String getDprice() {
        return (String) this.getAttributeValue("dprice");
    }

    /**
     * 设置 dprice 的属性值
     *
     * @param dprice the dprice to set
     * @since 2017年7月18日
     * @author
     */
    public void setDprice(String dprice) {
        this.setAttributeValue("dprice", dprice);
    }

    /**
     * 设置 vbfree1 的属性值
     *
     * @param vbfree1 the vbfree1 to set
     * @since 2017年7月18日
     * @author
     */
    public void setVbfree1(String vbfree1) {
        this.setAttributeValue("vbfree1", vbfree1);
    }

    /**
     * 设置 vbfree2 的属性值
     *
     * @param vbfree2 the vbfree2 to set
     * @since 2017年7月18日
     * @author
     */
    public void setVbfree2(String vbfree2) {
        this.setAttributeValue("vbfree2", vbfree2);
    }

    /**
     * 设置 vbfree3 的属性值
     *
     * @param vbfree3 the vbfree3 to set
     * @since 2017年7月18日
     * @author
     */
    public void setVbfree3(String vbfree3) {
        this.setAttributeValue("vbfree3", vbfree3);
    }

    /**
     * 设置 vbfree4 的属性值
     *
     * @param vbfree4 the vbfree4 to set
     * @since 2017年7月18日
     * @author
     */
    public void setVbfree4(String vbfree4) {
        this.setAttributeValue("vbfree4", vbfree4);
    }

    /**
     * <p>
     * 取得父VO主键字段.
     * <p>
     * 创建日期:
     *
     * @return java.lang.String
     */
    @Override
    public java.lang.String getParentPKFieldName() {
        return "ccostpriceid";
    }

    /**
     * 获得 vbfree1 的属性值
     *
     * @return the vbfree1
     * @since 2017年7月18日
     * @author
     */
    public String getVbfree1() {
        return (String) this.getAttributeValue("vbfree1");
    }

    /**
     * 获得 vbfree2 的属性值
     *
     * @return the vbfree2
     * @since 2017年7月18日
     * @author
     */
    public String getVbfree2() {
        return (String) this.getAttributeValue("vbfree2");
    }

    /**
     * 获得 vbfree3 的属性值
     *
     * @return the vbfree3
     * @since 2017年7月18日
     * @author
     */
    public String getVbfree3() {
        return (String) this.getAttributeValue("vbfree3");
    }

    /**
     * 获得 vbfree4 的属性值
     *
     * @return the vbfree4
     * @since 2017年7月18日
     * @author
     */
    public String getVbfree4() {
        return (String) this.getAttributeValue("vbfree4");
    }

    /**
     * <p>
     * 取得表主键.
     * <p>
     * 创建日期:
     *
     * @return java.lang.String
     */
    @Override
    public java.lang.String getPKFieldName() {
        return "ccostprice_bid";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     *
     * @return java.lang.String
     */
    @Override
    public java.lang.String getTableName() {
        return "mapub_costprice_b";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     *
     * @return java.lang.String
     */
    public static java.lang.String getDefaultTableName() {
        return "mapub_costprice_b";
    }

    /**
     * 按照默认方式创建构造子.
     * 创建日期:
     */
    public CostPriceBodyVO() {
        super();
    }

    @Override
    @nc.vo.annotation.MDEntityInfo(beanFullclassName = "nc.vo.mapub.costpricebase.entity.CostPriceBodyVO")
    public IVOMeta getMetaData() {
        IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("mapub.mapub_costprice_b");
        return meta;
    }
}
