/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mapub.costpricebase.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFDateTime;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 费用价格库主体VO </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 *
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CostPriceHeadVO extends SuperVO {

    public static String CCOSTPRICEID = "ccostpriceid";

    public static String PK_GROUP = "pk_group";

    public static String PK_ORG = "pk_org";

    public static String PK_ORG_V = "pk_org_v";

    public static String VPRICELIBCODE = "vpricelibcode";

    public static String VPRICELIBNAME = "vpricelibname";

    public static String ANNUAL = "annual";

    public static String VPERIOD = "vperiod";

    public static String VPRODUCTCODE = "vproductcode";

    public static String VPRODUCTNAME = "vproductname";

    public static String VREMARK = "vremark";

    public static String CREATOR = "creator";

    public static String CREATETIME = "createtime";

    public static String MODIFIER = "modifier";

    public static String MODIFIEDTIME = "modifiedtime";

    /**
     * 获得 ccostpriceid 的属性值
     *
     * @return the ccostpriceid
     * @since 2017年7月18日
     * @author
     */
    public String getCcostpriceid() {
        return (String) this.getAttributeValue("ccostpriceid");
    }

    /**
     * 设置 ccostpriceid 的属性值
     *
     * @param ccostpriceid the ccostpriceid to set
     * @since 2017年7月18日
     * @author
     */
    public void setCcostpriceid(String ccostpriceid) {
        this.setAttributeValue("ccostpriceid", ccostpriceid);
    }

    /**
     * 获得 pkGroup 的属性值
     *
     * @return the pkGroup
     * @since 2017年7月18日
     * @author
     */
    public String getPkGroup() {
        return (String) this.getAttributeValue("pk_group");
    }

    /**
     * 设置 pkGroup 的属性值
     *
     * @param pkGroup the pkGroup to set
     * @since 2017年7月18日
     * @author
     */
    public void setPkGroup(String pkGroup) {
        this.setAttributeValue("pk_group", pkGroup);
    }

    /**
     * 获得 pkOrg 的属性值
     *
     * @return the pkOrg
     * @since 2017年7月18日
     * @author
     */
    public String getPkOrg() {
        return (String) this.getAttributeValue("pk_org");
    }

    /**
     * 设置 pkOrg 的属性值
     *
     * @param pkOrg the pkOrg to set
     * @since 2017年7月18日
     * @author
     */
    public void setPkOrg(String pkOrg) {
        this.setAttributeValue("pk_org", pkOrg);
    }

    /**
     * 获得 pkOrgV 的属性值
     *
     * @return the pkOrgV
     * @since 2017年7月18日
     * @author
     */
    public String getPkOrgV() {
        return (String) this.getAttributeValue("pk_org_v");
    }

    /**
     * 设置 pkOrgV 的属性值
     *
     * @param pkOrgV the pkOrgV to set
     * @since 2017年7月18日
     * @author
     */
    public void setPkOrgV(String pkOrgV) {
        this.setAttributeValue("pk_org_v", pkOrgV);
    }

    /**
     * 获得 vpricelibcode 的属性值
     *
     * @return the vpricelibcode
     * @since 2017年7月18日
     * @author
     */
    public String getVpricelibcode() {
        return (String) this.getAttributeValue("vpricelibcode");
    }

    /**
     * 设置 vpricelibcode 的属性值
     *
     * @param vpricelibcode the vpricelibcode to set
     * @since 2017年7月18日
     * @author
     */
    public void setVpricelibcode(String vpricelibcode) {
        this.setAttributeValue("vpricelibcode", vpricelibcode);
    }

    /**
     * 获得 vpricelibname 的属性值
     *
     * @return the vpricelibname
     * @since 2017年7月18日
     * @author
     */
    public String getVpricelibname() {
        return (String) this.getAttributeValue("vpricelibname");
    }

    /**
     * 设置 vpricelibname 的属性值
     *
     * @param vpricelibname the vpricelibname to set
     * @since 2017年7月18日
     * @author
     */
    public void setVpricelibname(String vpricelibname) {
        this.setAttributeValue("vpricelibname", vpricelibname);
    }

    /**
     * 获得 annual 的属性值
     *
     * @return the annual
     * @since 2017年7月18日
     * @author
     */
    public String getAnnual() {
        return (String) this.getAttributeValue("annual");
    }

    /**
     * 设置 annual 的属性值
     *
     * @param annual the annual to set
     * @since 2017年7月18日
     * @author
     */
    public void setAnnual(String annual) {
        this.setAttributeValue("annual", annual);
    }

    /**
     * 获得 vperiod 的属性值
     *
     * @return the vperiod
     * @since 2017年7月18日
     * @author
     */
    public String getVperiod() {
        return (String) this.getAttributeValue("vperiod");
    }

    /**
     * 设置 vperiod 的属性值
     *
     * @param vperiod the vperiod to set
     * @since 2017年7月18日
     * @author
     */
    public void setVperiod(String vperiod) {
        this.setAttributeValue("vperiod", vperiod);
    }

    /**
     * 获得 vproductcode 的属性值
     *
     * @return the vproductcode
     * @since 2017年7月18日
     * @author
     */
    public String getVproductcode() {
        return (String) this.getAttributeValue("vproductcode");
    }

    /**
     * 设置 vproductcode 的属性值
     *
     * @param vproductcode the vproductcode to set
     * @since 2017年7月18日
     * @author
     */
    public void setVproductcode(String vproductcode) {
        this.setAttributeValue("vproductcode", vproductcode);
    }

    /**
     * 获得 vproductname 的属性值
     *
     * @return the vproductname
     * @since 2017年7月18日
     * @author
     */
    public String getVproductname() {
        return (String) this.getAttributeValue("vproductname");
    }

    /**
     * 设置 vproductname 的属性值
     *
     * @param vproductname the vproductname to set
     * @since 2017年7月18日
     * @author
     */
    public void setVproductname(String vproductname) {
        this.setAttributeValue("vproductname", vproductname);
    }

    /**
     * 获得 vremark 的属性值
     *
     * @return the vremark
     * @since 2017年7月18日
     * @author
     */
    public String getVremark() {
        return (String) this.getAttributeValue("vremark");
    }

    /**
     * 设置 vremark 的属性值
     *
     * @param vremark the vremark to set
     * @since 2017年7月18日
     * @author
     */
    public void setVremark(String vremark) {
        this.setAttributeValue("vremark", vremark);
    }

    /**
     * 获得 creator 的属性值
     *
     * @return the creator
     * @since 2017年7月18日
     * @author
     */
    public String getCreator() {
        return (String) this.getAttributeValue("creator");
    }

    /**
     * 设置 creator 的属性值
     *
     * @param creator the creator to set
     * @since 2017年7月18日
     * @author
     */
    public void setCreator(String creator) {
        this.setAttributeValue("creator", creator);
    }

    /**
     * 获得 createtime 的属性值
     *
     * @return the createtime
     * @since 2017年7月18日
     * @author
     */
    public UFDateTime getCreatetime() {
        return (UFDateTime) this.getAttributeValue("createtime");
    }

    /**
     * 设置 createtime 的属性值
     *
     * @param createtime the createtime to set
     * @since 2017年7月18日
     * @author
     */
    public void setCreatetime(UFDateTime createtime) {
        this.setAttributeValue("createtime", createtime);
    }

    /**
     * 获得 modifier 的属性值
     *
     * @return the modifier
     * @since 2017年7月18日
     * @author
     */
    public String getModifier() {
        return (String) this.getAttributeValue("modifier");
    }

    /**
     * 设置 modifier 的属性值
     *
     * @param modifier the modifier to set
     * @since 2017年7月18日
     * @author
     */
    public void setModifier(String modifier) {
        this.setAttributeValue("modifier", modifier);
    }

    /**
     * 获得 modifiedtime 的属性值
     *
     * @return the modifiedtime
     * @since 2017年7月18日
     * @author
     */
    public UFDateTime getModifiedtime() {
        return (UFDateTime) this.getAttributeValue("modifiedtime");
    }

    /**
     * 设置 modifiedtime 的属性值
     *
     * @param modifiedtime the modifiedtime to set
     * @since 2017年7月18日
     * @author
     */
    public void setModifiedtime(UFDateTime modifiedtime) {
        this.setAttributeValue("modifiedtime", modifiedtime);
    }

    /**
     * <p>
     * 取得父VO主键字段.
     * <p>
     * 创建日期:
     *
     * @return java.lang.String
     */
    @Override
    public java.lang.String getParentPKFieldName() {
        return null;
    }

    /**
     * <p>
     * 取得表主键.
     * <p>
     * 创建日期:
     *
     * @return java.lang.String
     */
    @Override
    public java.lang.String getPKFieldName() {
        return "ccostpriceid";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     *
     * @return java.lang.String
     */
    @Override
    public java.lang.String getTableName() {
        return "mapub_costprice";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     *
     * @return java.lang.String
     */
    public static java.lang.String getDefaultTableName() {
        return "mapub_costprice";
    }

    /**
     * 按照默认方式创建构造子.
     * 创建日期:
     */
    public CostPriceHeadVO() {
        super();
    }

    @Override
    @nc.vo.annotation.MDEntityInfo(beanFullclassName = "nc.vo.mapub.costpricebase.entity.CostPriceHeadVO")
    public IVOMeta getMetaData() {
        IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("mapub.mapub_costprice");
        return meta;
    }
}
