insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VY2',1,-1,null,null,0,1,null,-1,'N',null,-1,'vpricesource',0,'N',1,'N','Y',0,null,0,'vpricesource','mapub.mapub_materialpricebase_b.vpricesource',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',1,26,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VY3',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree9',0,'N',1,'N','N',0,null,0,'vbfree9','mapub.mapub_materialpricebase_b.vbfree9',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,23,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VY4',1,-1,null,null,0,1,null,-1,'N',null,-1,'vpricesourcenum',0,'N',1,'N','N',0,null,0,'vpricesourcenum','mapub.mapub_materialpricebase.vpricesourcenum',null,'N',0,null,'1002Z310000000010VY1','@@@@',0,null,null,null,'N',0,9,'mapub_materialpricebase','物料价格库',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VY5',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','Y',0,null,0,'modifier','mapub.mapub_materialpricebase.modifier',null,'N',0,null,'1002Z310000000010VY1','@@@@',2,null,null,null,'N',1,3,'creator','creator',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VY6',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree4',0,'N',1,'N','N',0,null,0,'vbfree4','mapub.mapub_materialpricebase_b.vbfree4',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,18,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VY7',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree1',0,'N',1,'N','N',0,null,0,'vbfree1','mapub.mapub_materialpricebase_b.vbfree1',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,15,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VY8',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',0,null,0,'pk_org','mapub.mapub_materialpricebase.pk_org',null,'N',1,null,'1002Z310000000010VY1','@@@@',0,'业务单元',null,null,'N',0,3,'mapub_materialpricebase','物料价格库',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VY9',1,-1,null,null,0,1,null,-1,'N',null,-1,'nprice',0,'N',1,'N','Y',0,null,0,'nprice','mapub.mapub_materialpricebase_b.nprice',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,'8,-100000000000000000000.00000000,100000000000000000000.00000000',null,null,'N',1,30,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYA',1,-1,null,null,0,1,null,-1,'N',null,-1,'denddate',0,'N',1,'N','Y',0,null,0,'denddate','mapub.mapub_materialpricebase.denddate',null,'N',0,null,'1002Z310000000010VY1','@@@@',0,null,null,null,'N',1,11,'mapub_materialpricebase','物料价格库',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYB',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccrrencyid',0,'N',1,'N','N',0,null,0,'ccrrencyid','mapub.mapub_materialpricebase.ccrrencyid',null,'N',0,null,'1002Z310000000010VY1','@@@@',0,null,null,null,'N',0,7,'mapub_materialpricebase','物料价格库',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYC',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialpriceid',0,'N',1,'N','N',0,null,0,'cmaterialpriceid','mapub.mapub_materialpricebase.cmaterialpriceid',null,'N',0,null,'1002Z310000000010VY1','@@@@',0,null,null,null,'N',0,1,'mapub_materialpricebase','物料价格库',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYD',1,-1,null,null,0,1,null,-1,'N',null,-1,'vpricesourcerealnum',0,'N',1,'N','N',0,null,0,'vpricesourcerealnum','mapub.mapub_materialpricebase_b.vpricesourcerealnum',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,29,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYE',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree7',0,'N',1,'N','N',0,null,0,'vbfree7','mapub.mapub_materialpricebase_b.vbfree7',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,21,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYF',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',0,null,0,'ts','mapub.mapub_materialpricebase.ts',null,'N',0,null,'1002Z310000000010VY1','@@@@',0,null,null,null,'N',0,14,'mapub_materialpricebase','物料价格库',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYG',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',0,null,0,'pk_org','mapub.mapub_materialpricebase_b.pk_org',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,4,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYH',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree10',0,'N',1,'N','N',0,null,0,'vbfree10','mapub.mapub_materialpricebase_b.vbfree10',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,24,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYI',1,-1,null,null,0,0,null,-1,'N',null,-1,'creator',0,'N',1,'N','Y',0,null,0,'creator','mapub.mapub_materialpricebase.creator',null,'N',0,null,'1002Z310000000010VY1','@@@@',2,null,null,null,'N',1,1,'creator','审计信息',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccustomerid',0,'N',1,'N','Y',0,null,0,'ccustomerid','mapub.mapub_materialpricebase_b.ccustomerid',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,'客户档案,code=N',null,null,'N',1,14,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYK',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree5',0,'N',1,'N','N',0,null,0,'vbfree5','mapub.mapub_materialpricebase_b.vbfree5',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,19,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYL',1,-1,null,null,0,0,null,-1,'N',null,-1,'cmeasdocid',0,'N',1,'N','Y',0,null,0,'cmeasdocid','mapub.mapub_materialpricebase_b.cmeasdocid',null,'N',1,null,'1002Z310000000010VY1','@@@@',1,'计量单位,code=N',null,null,'N',1,25,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,0,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYM',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprojectid',0,'N',1,'N','Y',0,null,0,'cprojectid','mapub.mapub_materialpricebase_b.cprojectid',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,'项目,code=N',null,null,'N',1,11,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYN',1,-1,null,null,0,1,null,-1,'N',null,-1,'dbegindate',0,'N',1,'N','Y',0,null,0,'dbegindate','mapub.mapub_materialpricebase.dbegindate',null,'N',1,null,'1002Z310000000010VY1','@@@@',0,null,null,null,'N',1,10,'mapub_materialpricebase','物料价格库',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYO',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',0,null,0,'pk_group','mapub.mapub_materialpricebase_b.pk_group',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,3,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYP',1,-1,'业务单元',null,0,1,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','Y',0,null,0,'pk_org_v','mapub.mapub_materialpricebase.pk_org_v',null,'N',0,null,'1002Z310000000010VY1','@@@@',0,null,'2UC000-000011',null,'N',0,4,'mapub_materialpricebase','物料价格库',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYQ',1,-1,'物料编码',null,0,1,null,-1,'Y',null,-1,'cmaterialid',0,'N',1,'Y','Y',0,null,0,'cmaterialid','mapub.mapub_materialpricebase_b.cmaterialid','cmeasdocid=pk_measdoc','N',1,null,'1002Z310000000010VY1','@@@@',1,'物料','138100110-0001',null,'N',1,6,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYR',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',0,null,0,'pk_group','mapub.mapub_materialpricebase.pk_group',null,'N',0,null,'1002Z310000000010VY1','@@@@',0,null,null,null,'N',0,2,'mapub_materialpricebase','物料价格库',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYS',1,-1,null,null,0,1,null,-1,'N',null,-1,'cproductorid',0,'N',1,'N','Y',0,null,0,'cproductorid','mapub.mapub_materialpricebase_b.cproductorid',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,'生产厂商(自定义档案),code=N',null,null,'N',1,13,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYT',1,-1,null,null,0,1,null,-1,'N',null,-1,'vnote',0,'N',1,'N','Y',0,null,0,'vnote','mapub.mapub_materialpricebase.vnote',null,'N',0,null,'1002Z310000000010VY1','@@@@',0,null,null,null,'N',1,12,'mapub_materialpricebase','物料价格库',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYU',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvendorid',0,'N',1,'N','Y',0,null,0,'cvendorid','mapub.mapub_materialpricebase_b.cvendorid',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,'供应商档案,code=N',null,null,'N',1,12,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYV',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialpriceid',0,'N',1,'N','N',0,null,0,'cmaterialpriceid','mapub.mapub_materialpricebase_b.cmaterialpriceid',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,2,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYW',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',0,null,0,'ts','mapub.mapub_materialpricebase_b.ts',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,31,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYX',1,-1,null,null,0,1,null,-1,'N',null,-1,'vpricesourcenum',0,'N',1,'N','N',0,null,0,'vpricesourcenum','mapub.mapub_materialpricebase_b.vpricesourcenum',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,27,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,200)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYY',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','Y',0,null,0,'creationtime','mapub.mapub_materialpricebase.creationtime',null,'N',0,null,'1002Z310000000010VY1','@@@@',2,null,null,null,'N',1,2,'creator','creator',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VYZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'vpricesourcereal',0,'N',1,'N','Y',0,null,0,'vpricesourcereal','mapub.mapub_materialpricebase_b.vpricesourcereal',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',1,28,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,0,1,'N',1,null,200)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZ0',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialprice_bid',0,'N',1,'N','N',0,null,0,'cmaterialprice_bid','mapub.mapub_materialpricebase_b.cmaterialprice_bid',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,1,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZ1',1,-1,null,null,0,1,null,-1,'N',null,-1,'vpricename',0,'N',1,'N','Y',0,null,0,'vpricename','mapub.mapub_materialpricebase.vpricename',null,'N',1,null,'1002Z310000000010VY1','@@@@',0,null,null,null,'N',1,6,'mapub_materialpricebase','物料价格库',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZ2',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree2',0,'N',1,'N','N',0,null,0,'vbfree2','mapub.mapub_materialpricebase_b.vbfree2',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,16,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZ3',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree6',0,'N',1,'N','N',0,null,0,'vbfree6','mapub.mapub_materialpricebase_b.vbfree6',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,20,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZ4',1,-1,null,'false',0,1,null,-1,'N',null,-1,'blockingflag',0,'N',1,'N','N',0,null,0,'blockingflag','mapub.mapub_materialpricebase.blockingflag',null,'N',0,null,'1002Z310000000010VY1','@@@@',0,null,null,null,'N',0,13,'mapub_materialpricebase','物料价格库',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZ5',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree3',0,'N',1,'N','N',0,null,0,'vbfree3','mapub.mapub_materialpricebase_b.vbfree3',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,17,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZ6',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','Y',0,null,0,'modifiedtime','mapub.mapub_materialpricebase.modifiedtime',null,'N',0,null,'1002Z310000000010VY1','@@@@',2,null,null,null,'N',1,4,'creator','creator',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZ7',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialvid',0,'N',1,'N','N',0,null,0,'cmaterialvid','mapub.mapub_materialpricebase_b.cmaterialvid',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,10,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZ8',1,-1,null,null,0,1,null,-1,'N',null,-1,'vpricecode',0,'N',1,'N','Y',0,null,0,'vpricecode','mapub.mapub_materialpricebase.vpricecode',null,'N',1,null,'1002Z310000000010VY1','@@@@',0,null,null,null,'N',1,5,'mapub_materialpricebase','物料价格库',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZ9',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',0,null,0,'pk_org_v','mapub.mapub_materialpricebase_b.pk_org_v',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,5,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZA',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree8',0,'N',1,'N','N',0,null,0,'vbfree8','mapub.mapub_materialpricebase_b.vbfree8',null,'N',0,null,'1002Z310000000010VY1','@@@@',1,null,null,null,'N',0,22,'itempks','价格库物料明细',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010VZB',1,-1,'默认价格来源',null,0,1,null,-1,'N',null,-1,'vpricesource',0,'N',1,'N','Y',0,null,0,'vpricesource','mapub.mapub_materialpricebase.vpricesource',null,'N',1,null,'1002Z310000000010VY1','@@@@',0,null,'138100110-0000',null,'N',1,8,'mapub_materialpricebase','物料价格库',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010Z0R',1,-1,null,null,0,0,null,-1,'N','cmaterialid',-1,'cmaterialid.materialtype',null,'N',1,'N','Y',0,null,0,'materialtype','uap.material_v.materialtype',null,'N',0,null,'1002Z310000000010VY1',null,1,null,null,null,'N',1,9,'itempks','itempks',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010Z0S',1,-1,null,null,0,0,null,-1,'N','cmaterialid',-1,'cmaterialid.materialspec',null,'N',1,'N','Y',0,null,0,'materialspec','uap.material_v.materialspec',null,'N',0,null,'1002Z310000000010VY1',null,1,null,null,null,'N',1,8,'itempks','itempks',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010Z0T',1,-1,null,null,0,0,null,-1,'N','cmaterialid',-1,'cmaterialid.name',null,'N',1,'N','Y',0,null,0,'name','uap.material_v.name',null,'N',1,null,'1002Z310000000010VY1',null,1,null,null,null,'N',1,7,'itempks','itempks',0,'2015-09-22 14:45:04','N',null,null,null,1,1,'N',1,null,100)
go

