insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPG',1,-1,null,null,0,0,null,-1,'N',null,-1,'creator',null,'N',1,'N','Y',0,null,0,'creator','mapub.mapub_coprodcoef.creator',null,'N',0,null,'1002Z310000000015LPF',null,2,null,null,null,'N',1,1,'AuditInfo','审计信息',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPH',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbomid',null,'N',1,'N','Y',0,null,0,'cbomid','mapub.mapub_coprodcoef.cbomid',null,'N',0,null,'1002Z310000000015LPF',null,0,null,null,null,'N',1,11,'mapub_coprodcoef','联产品相对系数',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPI',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org_v',null,'N',1,'N','Y',0,null,0,'pk_org_v','mapub.mapub_coprodcoef.pk_org_v',null,'N',0,null,'1002Z310000000015LPF',null,0,null,'1381001080001',null,'N',0,4,'mapub_coprodcoef','联产品相对系数',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPJ',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',null,'N',1,'N','Y',0,null,0,'creationtime','mapub.mapub_coprodcoef.creationtime',null,'N',0,null,'1002Z310000000015LPF',null,2,null,null,null,'N',1,2,'AuditInfo','AuditInfo',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPK',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',0,null,0,'pk_org','mapub.mapub_coprodcoef.pk_org',null,'N',0,null,'1002Z310000000015LPF',null,0,null,null,null,'N',0,3,'mapub_coprodcoef','联产品相对系数',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPL',1,-1,null,null,0,1,null,-1,'N',null,-1,'nrelcoefficient',null,'N',1,'N','Y',0,null,0,'nrelcoefficient','mapub.mapub_coprodcoef_b.nrelcoefficient',null,'N',0,null,'1002Z310000000015LPF',null,1,'8,0.00,100000000000000000000.00',null,null,'N',1,15,'itembpks','联产品相对系数明细',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPM',1,-1,null,null,0,1,null,-1,'N',null,-1,'celementid',null,'N',1,'N','Y',0,null,0,'celementid','mapub.mapub_coprodcoef_b.celementid',null,'N',0,null,'1002Z310000000015LPF',null,1,null,'1381001080007',null,'N',1,13,'itembpks','联产品相对系数明细',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPN',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccoprodcoefbid',null,'N',1,'N','N',0,null,0,'ccoprodcoefbid','mapub.mapub_coprodcoef_b.ccoprodcoefbid',null,'N',0,null,'1002Z310000000015LPF',null,1,null,null,null,'N',0,1,'itembpks','联产品相对系数明细',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPO',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialvid',null,'N',1,'N','N',0,null,0,'cmaterialvid','mapub.mapub_coprodcoef.cmaterialvid',null,'N',0,null,'1002Z310000000015LPF',null,0,null,null,null,'N',0,7,'mapub_coprodcoef','联产品相对系数',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPP',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',null,'N',1,'N','Y',0,null,0,'modifier','mapub.mapub_coprodcoef.modifier',null,'N',0,null,'1002Z310000000015LPF',null,2,null,'1381001080002',null,'N',1,3,'AuditInfo','AuditInfo',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'iproducttype',null,'N',1,'N','Y',0,null,0,'iproducttype','mapub.mapub_coprodcoef_b.iproducttype',null,'N',0,null,'1002Z310000000015LPF',null,1,null,null,null,'N',1,9,'itembpks','联产品相对系数明细',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPR',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_factorchart',null,'N',1,'N','Y',0,null,0,'pk_factorchart','mapub.mapub_coprodcoef.pk_factorchart',null,'N',0,null,'1002Z310000000015LPF',null,0,'要素表',null,null,'N',1,10,'mapub_coprodcoef','联产品相对系数',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPS',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',null,'N',1,'N','Y',0,null,0,'modifiedtime','mapub.mapub_coprodcoef.modifiedtime',null,'N',0,null,'1002Z310000000015LPF',null,2,null,'1381001080008',null,'N',1,4,'AuditInfo','AuditInfo',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPT',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialid',null,'N',1,'N','Y',0,null,0,'cmaterialid','mapub.mapub_coprodcoef_b.cmaterialid',null,'N',0,null,'1002Z310000000015LPF',null,1,null,'1381001080009',null,'N',1,6,'itembpks','联产品相对系数明细',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPU',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccosttypeid',null,'N',1,'N','N',0,null,0,'ccosttypeid','mapub.mapub_coprodcoef_b.ccosttypeid',null,'N',0,null,'1002Z310000000015LPF',null,1,null,null,null,'N',0,12,'itembpks','联产品相对系数明细',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPV',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_elementsystem',null,'N',1,'N','Y',0,null,0,'pk_elementsystem','mapub.mapub_coprodcoef.pk_elementsystem',null,'N',0,null,'1002Z310000000015LPF',null,0,null,'1381001080010',null,'N',1,8,'mapub_coprodcoef','联产品相对系数',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPW',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialid',null,'N',1,'N','Y',0,null,0,'cmaterialid','mapub.mapub_coprodcoef.cmaterialid',null,'N',0,null,'1002Z310000000015LPF',null,0,'物料,code=Y','1381001080011',null,'N',1,5,'mapub_coprodcoef','联产品相对系数',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPX',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',0,null,0,'ts','mapub.mapub_coprodcoef_b.ts',null,'N',0,null,'1002Z310000000015LPF',null,1,null,null,null,'N',0,16,'itembpks','联产品相对系数明细',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPY',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',0,null,0,'pk_group','mapub.mapub_coprodcoef_b.pk_group',null,'N',0,null,'1002Z310000000015LPF',null,1,null,null,null,'N',0,3,'itembpks','联产品相对系数明细',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LPZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',0,null,0,'pk_org','mapub.mapub_coprodcoef_b.pk_org',null,'N',0,null,'1002Z310000000015LPF',null,1,null,null,null,'N',0,4,'itembpks','联产品相对系数明细',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LQ0',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccostcenterid',null,'N',1,'N','Y',0,null,0,'ccostcenterid','mapub.mapub_coprodcoef_b.ccostcenterid',null,'N',0,null,'1002Z310000000015LPF',null,1,null,'1381001080012',null,'N',1,10,'itembpks','联产品相对系数明细',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LQ1',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccoprodcoefid',null,'N',1,'N','N',0,null,0,'ccoprodcoefid','mapub.mapub_coprodcoef.ccoprodcoefid',null,'N',0,null,'1002Z310000000015LPF',null,0,null,null,null,'N',0,1,'mapub_coprodcoef','联产品相对系数',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LQ2',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org_v',null,'N',1,'N','N',0,null,0,'pk_org_v','mapub.mapub_coprodcoef_b.pk_org_v',null,'N',0,null,'1002Z310000000015LPF',null,1,null,null,null,'N',0,5,'itembpks','联产品相对系数明细',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LQ3',1,-1,null,null,0,1,null,-1,'N',null,-1,'crtid',null,'N',1,'N','N',0,null,0,'crtid','mapub.mapub_coprodcoef.crtid',null,'N',0,null,'1002Z310000000015LPF',null,0,null,null,null,'N',0,9,'mapub_coprodcoef','联产品相对系数',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LQ4',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',0,null,0,'pk_group','mapub.mapub_coprodcoef.pk_group',null,'N',0,null,'1002Z310000000015LPF',null,0,null,null,null,'N',0,2,'mapub_coprodcoef','联产品相对系数',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LQ5',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',0,null,0,'ts','mapub.mapub_coprodcoef.ts',null,'N',0,null,'1002Z310000000015LPF',null,0,null,null,null,'N',0,13,'mapub_coprodcoef','联产品相对系数',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LQ6',1,-1,null,null,0,1,null,-1,'N',null,-1,'ibillstatus',null,'N',1,'N','N',0,null,0,'ibillstatus','mapub.mapub_coprodcoef.ibillstatus',null,'N',0,null,'1002Z310000000015LPF',null,0,null,null,null,'N',0,12,'mapub_coprodcoef','联产品相对系数',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LQ7',1,-1,null,null,0,0,null,-1,'N','cmaterialid',-1,'cmaterialid.name',null,'N',1,'N','Y',0,null,0,'name','uap.material_v.name',null,'N',1,null,'1002Z310000000015LPF',null,0,null,'1381001080003',null,'N',1,6,'mapub_coprodcoef','mapub_coprodcoef',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LQ8',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccoprodcoefid',null,'N',1,'N','N',0,null,0,'ccoprodcoefid','mapub.mapub_coprodcoef_b.ccoprodcoefid',null,'N',0,null,'1002Z310000000015LPF',null,1,null,null,null,'N',0,2,'itembpks','联产品相对系数明细',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LQ9',1,-1,null,null,0,1,null,-1,'N',null,-1,'cmaterialvid',null,'N',1,'N','N',0,null,0,'cmaterialvid','mapub.mapub_coprodcoef_b.cmaterialvid',null,'N',0,null,'1002Z310000000015LPF',null,1,null,null,null,'N',0,8,'itembpks','联产品相对系数明细',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LQE',1,-1,null,null,0,0,null,-1,'N','ccostcenterid',-1,'ccostcenterid.ccname',null,'N',1,'N','Y',0,null,0,'ccname','resa.resacostcenter.ccname',null,'N',0,null,'1002Z310000000015LPF',null,1,null,'1381001080004',null,'N',1,11,'itembpks','itembpks',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LQF',1,-1,null,null,0,0,null,-1,'N','cmaterialid',-1,'cmaterialid.name',null,'N',1,'N','Y',0,null,0,'name','uap.material_v.name',null,'N',0,null,'1002Z310000000015LPF',null,1,null,'1381001080005',null,'N',1,7,'itembpks','itembpks',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000015LQG',1,-1,null,null,0,0,null,-1,'N','celementid',-1,'celementid.factorname',null,'N',1,'N','Y',0,null,0,'factorname','resa.FactorAsoa.factorname',null,'N',0,null,'1002Z310000000015LPF',null,1,null,'1381001080006',null,'N',1,14,'itembpks','itembpks',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,100)
go

