insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value,ext1) values('1001ZA100000000033VU','工厂',5,1,1,null,null,'pk_org','工厂',null,'N','Y','N','N','N','N','N',null,'Y','N','N','N','N','N','Y',null,'Y',9999,null,'=','等于@',0,'@@@@','1001ZA100000000033VT',null,'238100110-00010',2,null,null,'2015-04-21 11:31:48','N',null,null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value,ext1) values('1001ZA100000000033VX','-99',9,2,1,null,null,'vname','成本动因名称',null,'N','N','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001ZA100000000033VT',null,'238100110-00007',2,null,null,'2015-04-21 11:31:48','N',null,null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value,ext1) values('1001ZA100000000033VY','管控范围',5,0,1,null,null,'ccontrolscope','管控范围',null,'N','Y','N','Y','N','N','N','N','Y','Y','N','N','N','N','N',null,'N',9999,null,'==','等于@',0,'@@@@','1001ZA100000000033VT',null,'238100110-00011',2,null,null,'2015-04-21 11:31:48','N',null,null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value,ext1) values('1001ZA1000000000367B','-99',0,3,1,null,null,'vcode','成本动因编码',null,'N','N','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1001ZA100000000033VT',null,'238100110-00006',2,null,null,'2015-04-21 11:31:48','N',null,null)
go

