insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000002CVT',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',0,null,0,'pk_group','cm.cm_driver.pk_group',null,'N',0,null,'1002ZA10000000004E6K','@@@@',0,null,null,null,'N',0,8,'cm_driver','成本动因',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000002CVU',1,-1,null,null,0,0,null,-1,'N',null,-1,'vformulacode',0,'N',1,'N','N',0,null,0,'vformulacode','cm.cm_driver.vformulacode',null,'N',0,null,'1002ZA10000000004E6K','@@@@',0,null,null,null,'N',0,10,'cm_driver','成本动因',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000002CVV',1,-1,null,null,0,1,null,-1,'N',null,-1,'vname',0,'N',1,'N','Y',0,null,0,'vname','cm.cm_driver.vname',null,'N',1,null,'1002ZA10000000004E6K','@@@@',0,null,'238100110-00007',null,'N',1,3,'cm_driver','成本动因',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,2)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000002CVW',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',0,null,0,'pk_org_v','cm.cm_driver.pk_org_v',null,'N',0,null,'1002ZA10000000004E6K','@@@@',0,null,null,null,'N',0,9,'cm_driver','成本动因',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000002CVX',1,-1,null,null,0,1,null,-1,'N',null,-1,'vformulavalue',0,'N',1,'N','Y',0,null,0,'vformulavalue','cm.cm_driver.vformulavalue',null,'Y',1,null,'1002ZA10000000004E6K','@@@@',0,null,null,null,'N',1,4,'cm_driver','成本动因',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000002CVY',1,-1,null,null,0,1,null,-1,'N',null,-1,'vjavapath',0,'N',1,'N','N',0,null,0,'vjavapath','cm.cm_driver.vjavapath',null,'Y',0,null,'1002ZA10000000004E6K','@@@@',0,null,null,null,'N',0,5,'cm_driver','成本动因',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000002CVZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'vnote',0,'N',1,'N','Y',0,null,0,'vnote','cm.cm_driver.vnote',null,'Y',0,null,'1002ZA10000000004E6K','@@@@',0,null,null,null,'N',1,6,'cm_driver','成本动因',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,3)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000002CW0',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',0,null,0,'ts','cm.cm_driver.ts',null,'N',0,null,'1002ZA10000000004E6K','@@@@',0,null,null,null,'N',0,11,'cm_driver','成本动因',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000002CW1',1,-1,null,null,0,1,null,-1,'N',null,-1,'cdriverid',0,'N',1,'N','N',0,null,0,'cdriverid','cm.cm_driver.cdriverid',null,'N',0,null,'1002ZA10000000004E6K','@@@@',0,null,null,null,'N',0,7,'cm_driver','成本动因',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000002CW2',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',0,null,0,'pk_org','cm.cm_driver.pk_org',null,'N',0,null,'1002ZA10000000004E6K','@@@@',0,null,null,null,'N',0,1,'cm_driver','成本动因',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000002CW3',1,-1,null,null,0,1,null,-1,'N',null,-1,'vcode',0,'N',1,'N','Y',0,null,0,'vcode','cm.cm_driver.vcode',null,'N',1,null,'1002ZA10000000004E6K','@@@@',0,null,'238100110-00006',null,'N',1,2,'cm_driver','成本动因',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA10000000004E6P',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',0,'N',1,'N','Y',0,null,0,'creationtime','cm.cm_driver.creationtime',null,'N',0,null,'1002ZA10000000004E6K','@@@@',2,null,null,null,'N',1,2,'tail','审计信息',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA10000000004E6T',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',0,'N',1,'N','Y',0,null,0,'modifiedtime','cm.cm_driver.modifiedtime',null,'N',0,null,'1002ZA10000000004E6K','@@@@',2,null,null,null,'N',1,4,'tail','审计信息',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA10000000004E6V',1,-1,null,null,0,0,null,-1,'N',null,-1,'creator',0,'N',1,'N','Y',0,null,0,'creator','cm.cm_driver.creator',null,'N',0,null,'1002ZA10000000004E6K','@@@@',2,null,null,null,'N',1,1,'tail','审计信息',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA10000000004E6W',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',0,'N',1,'N','Y',0,null,0,'modifier','cm.cm_driver.modifier',null,'N',0,null,'1002ZA10000000004E6K','@@@@',2,null,null,null,'N',1,3,'tail','审计信息',0,'2015-04-21 11:31:48','N',null,null,null,1,1,'N',1,null,1)
go

