/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mapub.costtype.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CostTypeVO extends SuperVO {

    public static final String CCOSTTYPEID = "ccosttypeid";

    public static final String PK_GROUP = "pk_group";

    public static final String PK_ORG = "pk_org";

    public static final String VCOSTTYPECODE = "vcosttypecode";

    public static final String VCOSTTYPENAME = "vcosttypename";

    public static final String BSCRAPFACTOR = "bscrapfactor";

    public static final String BSHRINKFACTOR = "bshrinkfactor";

    public static final String PK_ELEMENTSYSTEM = "pk_elementsystem";

    public static final String PK_FACTORCHART = "pk_factorchart";

    public static final String PK_MATERIALDOCVIEW = "pk_materialdocview";

    public static final String PK_ACTIVITYDOCVIEW = "pk_activitydocview";

    public static final String VMATERIALPRICESOURCE = "vmaterialpricesource";

    public static final String VMATERIALPRICESOURCENUM = "vmaterialpricesourcenum";

    public static final String VCOSTPRICESOURCE = "vcostpricesource";

    public static final String VCOSTPRICESOURCENUM = "vcostpricesourcenum";

    public static final String CBEGINMONTH = "cbeginmonth";

    public static final String CENDMONTH = "cendmonth";

    public static final String BDEFAULT = "bdefault";

    public static final String BCOMPUTE = "bcompute";

    public static final String BCREATETABLE = "bcreatetable";

    public static final String CREATOR = "creator";

    public static final String MODIFIER = "modifier";

    public static final String CREATIONTIME = "creationtime";

    public static final String MODIFIEDTIME = "modifiedtime";

    public static final String VNOTE = "vnote";

    public static final String VCOSTTYPENAME2 = "vcosttypename2";

    public static final String VCOSTTYPENAME3 = "vcosttypename3";

    public static final String VCOSTTYPENAME4 = "vcosttypename4";

    public static final String VCOSTTYPENAME5 = "vcosttypename5";

    public static final String VCOSTTYPENAME6 = "vcosttypename6";

    /**
     * 属性ccosttypeid的Getter方法.属性名：成本类型主键
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCcosttypeid() {
        return (java.lang.String) this.getAttributeValue("ccosttypeid");
    }

    /**
     * 属性ccosttypeid的Setter方法.属性名：成本类型主键
     * 创建日期:
     * 
     * @param newCcosttypeid java.lang.String
     */
    public void setCcosttypeid(java.lang.String newCcosttypeid) {
        this.setAttributeValue("ccosttypeid", newCcosttypeid);
    }

    /**
     * 属性pk_group的Getter方法.属性名：集团
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_group() {
        return (java.lang.String) this.getAttributeValue("pk_group");
    }

    /**
     * 属性pk_group的Setter方法.属性名：集团
     * 创建日期:
     * 
     * @param newPk_group java.lang.String
     */
    public void setPk_group(java.lang.String newPk_group) {
        this.setAttributeValue("pk_group", newPk_group);
    }

    /**
     * 属性pk_org的Getter方法.属性名：工厂
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org() {
        return (java.lang.String) this.getAttributeValue("pk_org");
    }

    /**
     * 属性pk_org的Setter方法.属性名：工厂
     * 创建日期:
     * 
     * @param newPk_org java.lang.String
     */
    public void setPk_org(java.lang.String newPk_org) {
        this.setAttributeValue("pk_org", newPk_org);
    }

    /**
     * 属性vcosttypecode的Getter方法.属性名：成本类型编码
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVcosttypecode() {
        return (java.lang.String) this.getAttributeValue("vcosttypecode");
    }

    /**
     * 属性vcosttypecode的Setter方法.属性名：成本类型编码
     * 创建日期:
     * 
     * @param newVcosttypecode java.lang.String
     */
    public void setVcosttypecode(java.lang.String newVcosttypecode) {
        this.setAttributeValue("vcosttypecode", newVcosttypecode);
    }

    /**
     * 属性vcosttypename的Getter方法.属性名：成本类型名称
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVcosttypename() {
        return (java.lang.String) this.getAttributeValue("vcosttypename");
    }

    /**
     * 属性vcosttypename的Setter方法.属性名：成本类型名称
     * 创建日期:
     * 
     * @param newVcosttypename java.lang.String
     */
    public void setVcosttypename(java.lang.String newVcosttypename) {
        this.setAttributeValue("vcosttypename", newVcosttypename);
    }

    /**
     * 属性bscrapfactor的Getter方法.属性名：是否考虑废品系数
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getBscrapfactor() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("bscrapfactor");
    }

    /**
     * 属性bscrapfactor的Setter方法.属性名：是否考虑废品系数
     * 创建日期:
     * 
     * @param newBscrapfactor nc.vo.pub.lang.UFBoolean
     */
    public void setBscrapfactor(nc.vo.pub.lang.UFBoolean newBscrapfactor) {
        this.setAttributeValue("bscrapfactor", newBscrapfactor);
    }

    /**
     * 属性bshrinkfactor的Getter方法.属性名：是否考虑损耗系数
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getBshrinkfactor() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("bshrinkfactor");
    }

    /**
     * 属性bshrinkfactor的Setter方法.属性名：是否考虑损耗系数
     * 创建日期:
     * 
     * @param newBshrinkfactor nc.vo.pub.lang.UFBoolean
     */
    public void setBshrinkfactor(nc.vo.pub.lang.UFBoolean newBshrinkfactor) {
        this.setAttributeValue("bshrinkfactor", newBshrinkfactor);
    }

    /**
     * 属性pk_elementsystem的Getter方法.属性名：核算要素体系
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_elementsystem() {
        return (java.lang.String) this.getAttributeValue("pk_elementsystem");
    }

    /**
     * 属性pk_elementsystem的Setter方法.属性名：核算要素体系
     * 创建日期:
     * 
     * @param newPk_elementsystem java.lang.String
     */
    public void setPk_elementsystem(java.lang.String newPk_elementsystem) {
        this.setAttributeValue("pk_elementsystem", newPk_elementsystem);
    }

    /**
     * 属性pk_factorchart的Getter方法.属性名：核算要素表
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_factorchart() {
        return (java.lang.String) this.getAttributeValue("pk_factorchart");
    }

    /**
     * 属性pk_factorchart的Setter方法.属性名：核算要素表
     * 创建日期:
     * 
     * @param newPk_factorchart java.lang.String
     */
    public void setPk_factorchart(java.lang.String newPk_factorchart) {
        this.setAttributeValue("pk_factorchart", newPk_factorchart);
    }

    /**
     * 属性pk_materialdocview的Getter方法.属性名：要素与物料对照表
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_materialdocview() {
        return (java.lang.String) this.getAttributeValue("pk_materialdocview");
    }

    /**
     * 属性pk_materialdocview的Setter方法.属性名：要素与物料对照表
     * 创建日期:
     * 
     * @param newPk_materialdocview java.lang.String
     */
    public void setPk_materialdocview(java.lang.String newPk_materialdocview) {
        this.setAttributeValue("pk_materialdocview", newPk_materialdocview);
    }

    /**
     * 属性pk_activitydocview的Getter方法.属性名：要素与作业对照表
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_activitydocview() {
        return (java.lang.String) this.getAttributeValue("pk_activitydocview");
    }

    /**
     * 属性pk_activitydocview的Setter方法.属性名：要素与作业对照表
     * 创建日期:
     * 
     * @param newPk_activitydocview java.lang.String
     */
    public void setPk_activitydocview(java.lang.String newPk_activitydocview) {
        this.setAttributeValue("pk_activitydocview", newPk_activitydocview);
    }

    /**
     * 属性vmaterialpricesource的Getter方法.属性名：材料价格来源
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVmaterialpricesource() {
        return (java.lang.String) this.getAttributeValue("vmaterialpricesource");
    }

    /**
     * 属性vmaterialpricesource的Setter方法.属性名：材料价格来源
     * 创建日期:
     * 
     * @param newVmaterialpricesource java.lang.String
     */
    public void setVmaterialpricesource(java.lang.String newVmaterialpricesource) {
        this.setAttributeValue("vmaterialpricesource", newVmaterialpricesource);
    }

    /**
     * 属性vmaterialpricesourcenum的Getter方法.属性名：材料价格来源数
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVmaterialpricesourcenum() {
        return (java.lang.String) this.getAttributeValue("vmaterialpricesourcenum");
    }

    /**
     * 属性vmaterialpricesourcenum的Setter方法.属性名：材料价格来源数
     * 创建日期:
     * 
     * @param newVmaterialpricesourcenum java.lang.String
     */
    public void setVmaterialpricesourcenum(java.lang.String newVmaterialpricesourcenum) {
        this.setAttributeValue("vmaterialpricesourcenum", newVmaterialpricesourcenum);
    }

    /**
     * 属性vcostpricesource的Getter方法.属性名：费用价格来源
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVcostpricesource() {
        return (java.lang.String) this.getAttributeValue("vcostpricesource");
    }

    /**
     * 属性vcostpricesource的Setter方法.属性名：费用价格来源
     * 创建日期:
     * 
     * @param newVcostpricesource java.lang.String
     */
    public void setVcostpricesource(java.lang.String newVcostpricesource) {
        this.setAttributeValue("vcostpricesource", newVcostpricesource);
    }

    /**
     * 属性vcostpricesourcenum的Getter方法.属性名：费用价格来源数
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVcostpricesourcenum() {
        return (java.lang.String) this.getAttributeValue("vcostpricesourcenum");
    }

    /**
     * 属性vcostpricesourcenum的Setter方法.属性名：费用价格来源数
     * 创建日期:
     * 
     * @param newVcostpricesourcenum java.lang.String
     */
    public void setVcostpricesourcenum(java.lang.String newVcostpricesourcenum) {
        this.setAttributeValue("vcostpricesourcenum", newVcostpricesourcenum);
    }

    /**
     * 属性cbeginmonth的Getter方法.属性名：生效日期
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDate
     */
    public nc.vo.pub.lang.UFDate getCbeginmonth() {
        return (nc.vo.pub.lang.UFDate) this.getAttributeValue("cbeginmonth");
    }

    /**
     * 属性cbeginmonth的Setter方法.属性名：生效日期
     * 创建日期:
     * 
     * @param newCbeginmonth nc.vo.pub.lang.UFDate
     */
    public void setCbeginmonth(nc.vo.pub.lang.UFDate newCbeginmonth) {
        this.setAttributeValue("cbeginmonth", newCbeginmonth);
    }

    /**
     * 属性cendmonth的Getter方法.属性名：失效日期
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDate
     */
    public nc.vo.pub.lang.UFDate getCendmonth() {
        return (nc.vo.pub.lang.UFDate) this.getAttributeValue("cendmonth");
    }

    /**
     * 属性cendmonth的Setter方法.属性名：失效日期
     * 创建日期:
     * 
     * @param newCendmonth nc.vo.pub.lang.UFDate
     */
    public void setCendmonth(nc.vo.pub.lang.UFDate newCendmonth) {
        this.setAttributeValue("cendmonth", newCendmonth);
    }

    /**
     * 属性bdefault的Getter方法.属性名：是否默认
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getBdefault() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("bdefault");
    }

    /**
     * 属性bdefault的Setter方法.属性名：是否默认
     * 创建日期:
     * 
     * @param newBdefault nc.vo.pub.lang.UFBoolean
     */
    public void setBdefault(nc.vo.pub.lang.UFBoolean newBdefault) {
        this.setAttributeValue("bdefault", newBdefault);
    }

    /**
     * 属性bcompute的Getter方法.属性名：是否已计算
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getBcompute() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("bcompute");
    }

    /**
     * 属性bcompute的Setter方法.属性名：是否已计算
     * 创建日期:
     * 
     * @param newBcompute nc.vo.pub.lang.UFBoolean
     */
    public void setBcompute(nc.vo.pub.lang.UFBoolean newBcompute) {
        this.setAttributeValue("bcompute", newBcompute);
    }

    /**
     * 属性bcreatetable的Getter方法.属性名：是否已生成库
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFBoolean
     */
    public nc.vo.pub.lang.UFBoolean getBcreatetable() {
        return (nc.vo.pub.lang.UFBoolean) this.getAttributeValue("bcreatetable");
    }

    /**
     * 属性bcreatetable的Setter方法.属性名：是否已生成库
     * 创建日期:
     * 
     * @param newBcreatetable nc.vo.pub.lang.UFBoolean
     */
    public void setBcreatetable(nc.vo.pub.lang.UFBoolean newBcreatetable) {
        this.setAttributeValue("bcreatetable", newBcreatetable);
    }

    /**
     * 属性creator的Getter方法.属性名：创建人
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCreator() {
        return (java.lang.String) this.getAttributeValue("creator");
    }

    /**
     * 属性creator的Setter方法.属性名：创建人
     * 创建日期:
     * 
     * @param newCreator java.lang.String
     */
    public void setCreator(java.lang.String newCreator) {
        this.setAttributeValue("creator", newCreator);
    }

    /**
     * 属性modifier的Getter方法.属性名：修改人
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getModifier() {
        return (java.lang.String) this.getAttributeValue("modifier");
    }

    /**
     * 属性modifier的Setter方法.属性名：修改人
     * 创建日期:
     * 
     * @param newModifier java.lang.String
     */
    public void setModifier(java.lang.String newModifier) {
        this.setAttributeValue("modifier", newModifier);
    }

    /**
     * 属性creationtime的Getter方法.属性名：创建时间
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getCreationtime() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("creationtime");
    }

    /**
     * 属性creationtime的Setter方法.属性名：创建时间
     * 创建日期:
     * 
     * @param newCreationtime nc.vo.pub.lang.UFDateTime
     */
    public void setCreationtime(nc.vo.pub.lang.UFDateTime newCreationtime) {
        this.setAttributeValue("creationtime", newCreationtime);
    }

    /**
     * 属性modifiedtime的Getter方法.属性名：修改时间
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getModifiedtime() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("modifiedtime");
    }

    /**
     * 属性modifiedtime的Setter方法.属性名：修改时间
     * 创建日期:
     * 
     * @param newModifiedtime nc.vo.pub.lang.UFDateTime
     */
    public void setModifiedtime(nc.vo.pub.lang.UFDateTime newModifiedtime) {
        this.setAttributeValue("modifiedtime", newModifiedtime);
    }

    /**
     * 属性vnote的Getter方法.属性名：备注
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVnote() {
        return (java.lang.String) this.getAttributeValue("vnote");
    }

    /**
     * 属性vnote的Setter方法.属性名：备注
     * 创建日期:
     * 
     * @param newVnote java.lang.String
     */
    public void setVnote(java.lang.String newVnote) {
        this.setAttributeValue("vnote", newVnote);
    }

    /**
     * 属性dr的Getter方法.属性名：dr
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getDr() {
        return (java.lang.Integer) this.getAttributeValue("dr");
    }

    /**
     * 属性dr的Setter方法.属性名：dr
     * 创建日期:
     * 
     * @param newDr java.lang.Integer
     */
    public void setDr(java.lang.Integer newDr) {
        this.setAttributeValue("dr", newDr);
    }

    /**
     * 属性ts的Getter方法.属性名：ts
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getTs() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("ts");
    }

    /**
     * 属性ts的Setter方法.属性名：ts
     * 创建日期:
     * 
     * @param newTs nc.vo.pub.lang.UFDateTime
     */
    public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
        this.setAttributeValue("ts", newTs);
    }

    /**
     * <p>
     * 取得父VO主键字段.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getParentPKFieldName() {
        return null;
    }

    /**
     * <p>
     * 取得表主键.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getPKFieldName() {
        return "ccosttypeid";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getTableName() {
        return "mapub_costtype";
    }

    /**
     * 按照默认方式创建构造子.
     * 创建日期:
     */
    public CostTypeVO() {
        super();
    }

    @Override
    @nc.vo.annotation.MDEntityInfo(beanFullclassName = "nc.vo.mapub.costtype.entity.CostTypeVO")
    public IVOMeta getMetaData() {
        IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("mapub.mapub_costtype");
        return meta;
    }

    /**
     * @return
     */
    public static String getDefaultTableName() {
        return "mapub_costtype";
    }
}
