/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mapub.acquirepricelog.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class AcquirePriceLogVO extends SuperVO {

    public static final String PK_LOG = "pk_log";

    public static final String VACQUIRETYPE = "vacquiretype";

    public static final String PK_GROUP = "pk_group";

    public static final String PK_ORG = "pk_org";

    public static final String CCOSTTYPEID = "ccosttypeid";

    public static final String CPERIOD = "cperiod";

    public static final String BEGINDATE = "begindate";

    public static final String ENDDATE = "enddate";

    public static final String ISOURCETYPE = "isourcetype";

    public static final String PRIORITYLEVEL = "prioritylevel";

    public static final String CMATERIALPRICEID = "cmaterialpriceid";

    public static final String PK_CURRTYPE = "pk_currtype";

    public static final String FINSTORAGETYPE = "finstoragetype";

    public static final String CCOSTCENTERID = "ccostcenterid";

    public static final String CMATERIALID = "cmaterialid";

    public static final String CPROJECTID = "cprojectid";

    public static final String CVENDORID = "cvendorid";

    public static final String CPRODUCTORID = "cproductorid";

    public static final String CCUSTOMERID = "ccustomerid";

    public static final String VFREE1 = "vfree1";

    public static final String VFREE2 = "vfree2";

    public static final String VFREE3 = "vfree3";

    public static final String VFREE4 = "vfree4";

    public static final String VFREE5 = "vfree5";

    public static final String VFREE6 = "vfree6";

    public static final String VFREE7 = "vfree7";

    public static final String VFREE8 = "vfree8";

    public static final String VFREE9 = "vfree9";

    public static final String VFREE10 = "vfree10";

    public static final String CBCOSTCENTERID = "cbcostcenterid";

    public static final String CBMATERIALID = "cbmaterialid";

    public static final String CBPROJECTID = "cbprojectid";

    public static final String CBVENDORID = "cbvendorid";

    public static final String CBPRODUCTORID = "cbproductorid";

    public static final String CBCUSTOMERID = "cbcustomerid";

    public static final String VBFREE1 = "vbfree1";

    public static final String VBFREE2 = "vbfree2";

    public static final String VBFREE3 = "vbfree3";

    public static final String VBFREE4 = "vbfree4";

    public static final String VBFREE5 = "vbfree5";

    public static final String VBFREE6 = "vbfree6";

    public static final String VBFREE7 = "vbfree7";

    public static final String VBFREE8 = "vbfree8";

    public static final String VBFREE9 = "vbfree9";

    public static final String VBFREE10 = "vbfree10";

    public static final String CELEMENTID = "celementid";

    public static final String CACTIVITYID = "cactivityid";

    public static final String PK_GROUP_ACTUAL = "pk_group_actual";

    public static final String PK_ORG_ACTUAL = "pk_org_actual";

    public static final String ISOURCETYPE_ACTUAL = "isourcetype_actual";

    public static final String CMATERIALPRICEID_ACTUAL = "cmaterialpriceid_actual";

    public static final String PK_CURRTYPE_ACTUAL = "pk_currtype_actual";

    public static final String NPRICE = "nprice";

    public static final String ERRORINFO = "errorinfo";

    public static final String SOLVEPLAN = "solveplan";

    /**
     * 属性pk_log的Getter方法.属性名：取价错误日志
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_log() {
        return (java.lang.String) this.getAttributeValue("pk_log");
    }

    /**
     * 属性pk_log的Setter方法.属性名：取价错误日志
     * 创建日期:
     * 
     * @param newPk_log java.lang.String
     */
    public void setPk_log(java.lang.String newPk_log) {
        this.setAttributeValue("pk_log", newPk_log);
    }

    /**
     * 属性vacquiretype的Getter方法.属性名：取价类型
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVacquiretype() {
        return (java.lang.String) this.getAttributeValue("vacquiretype");
    }

    /**
     * 属性vacquiretype的Setter方法.属性名：取价类型
     * 创建日期:
     * 
     * @param newVacquiretype java.lang.String
     */
    public void setVacquiretype(java.lang.String newVacquiretype) {
        this.setAttributeValue("vacquiretype", newVacquiretype);
    }

    /**
     * 属性pk_group的Getter方法.属性名：取价集团
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_group() {
        return (java.lang.String) this.getAttributeValue("pk_group");
    }

    /**
     * 属性pk_group的Setter方法.属性名：取价集团
     * 创建日期:
     * 
     * @param newPk_group java.lang.String
     */
    public void setPk_group(java.lang.String newPk_group) {
        this.setAttributeValue("pk_group", newPk_group);
    }

    /**
     * 属性pk_org的Getter方法.属性名：取价工厂
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org() {
        return (java.lang.String) this.getAttributeValue("pk_org");
    }

    /**
     * 属性pk_org的Setter方法.属性名：取价工厂
     * 创建日期:
     * 
     * @param newPk_org java.lang.String
     */
    public void setPk_org(java.lang.String newPk_org) {
        this.setAttributeValue("pk_org", newPk_org);
    }

    /**
     * 属性ccosttypeid的Getter方法.属性名：成本类型
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCcosttypeid() {
        return (java.lang.String) this.getAttributeValue("ccosttypeid");
    }

    /**
     * 属性ccosttypeid的Setter方法.属性名：成本类型
     * 创建日期:
     * 
     * @param newCcosttypeid java.lang.String
     */
    public void setCcosttypeid(java.lang.String newCcosttypeid) {
        this.setAttributeValue("ccosttypeid", newCcosttypeid);
    }

    /**
     * 属性cperiod的Getter方法.属性名：会计期间
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCperiod() {
        return (java.lang.String) this.getAttributeValue("cperiod");
    }

    /**
     * 属性cperiod的Setter方法.属性名：会计期间
     * 创建日期:
     * 
     * @param newCperiod java.lang.String
     */
    public void setCperiod(java.lang.String newCperiod) {
        this.setAttributeValue("cperiod", newCperiod);
    }

    /**
     * 属性begindate的Getter方法.属性名：开始期间
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getBegindate() {
        return (java.lang.String) this.getAttributeValue("begindate");
    }

    /**
     * 属性begindate的Setter方法.属性名：开始期间
     * 创建日期:
     * 
     * @param newBegindate java.lang.String
     */
    public void setBegindate(java.lang.String newBegindate) {
        this.setAttributeValue("begindate", newBegindate);
    }

    /**
     * 属性enddate的Getter方法.属性名：截止期间
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getEnddate() {
        return (java.lang.String) this.getAttributeValue("enddate");
    }

    /**
     * 属性enddate的Setter方法.属性名：截止期间
     * 创建日期:
     * 
     * @param newEnddate java.lang.String
     */
    public void setEnddate(java.lang.String newEnddate) {
        this.setAttributeValue("enddate", newEnddate);
    }

    /**
     * 属性isourcetype的Getter方法.属性名：来源类型
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getIsourcetype() {
        return (java.lang.Integer) this.getAttributeValue("isourcetype");
    }

    /**
     * 属性isourcetype的Setter方法.属性名：来源类型
     * 创建日期:
     * 
     * @param newIsourcetype java.lang.Integer
     */
    public void setIsourcetype(java.lang.Integer newIsourcetype) {
        this.setAttributeValue("isourcetype", newIsourcetype);
    }

    /**
     * 属性prioritylevel的Getter方法.属性名：优先级
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPrioritylevel() {
        return (java.lang.String) this.getAttributeValue("prioritylevel");
    }

    /**
     * 属性prioritylevel的Setter方法.属性名：优先级
     * 创建日期:
     * 
     * @param newPrioritylevel java.lang.String
     */
    public void setPrioritylevel(java.lang.String newPrioritylevel) {
        this.setAttributeValue("prioritylevel", newPrioritylevel);
    }

    /**
     * 属性cmaterialpriceid的Getter方法.属性名：价格库
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCmaterialpriceid() {
        return (java.lang.String) this.getAttributeValue("cmaterialpriceid");
    }

    /**
     * 属性cmaterialpriceid的Setter方法.属性名：价格库
     * 创建日期:
     * 
     * @param newCmaterialpriceid java.lang.String
     */
    public void setCmaterialpriceid(java.lang.String newCmaterialpriceid) {
        this.setAttributeValue("cmaterialpriceid", newCmaterialpriceid);
    }

    /**
     * 属性pk_currtype的Getter方法.属性名：来源币种
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_currtype() {
        return (java.lang.String) this.getAttributeValue("pk_currtype");
    }

    /**
     * 属性pk_currtype的Setter方法.属性名：来源币种
     * 创建日期:
     * 
     * @param newPk_currtype java.lang.String
     */
    public void setPk_currtype(java.lang.String newPk_currtype) {
        this.setAttributeValue("pk_currtype", newPk_currtype);
    }

    /**
     * 属性finstoragetype的Getter方法.属性名：入库类型
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getFinstoragetype() {
        return (java.lang.Integer) this.getAttributeValue("finstoragetype");
    }

    /**
     * 属性finstoragetype的Setter方法.属性名：入库类型
     * 创建日期:
     * 
     * @param newFinstoragetype java.lang.Integer
     */
    public void setFinstoragetype(java.lang.Integer newFinstoragetype) {
        this.setAttributeValue("finstoragetype", newFinstoragetype);
    }

    /**
     * 属性ccostcenterid的Getter方法.属性名：主产品成本中心
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCcostcenterid() {
        return (java.lang.String) this.getAttributeValue("ccostcenterid");
    }

    /**
     * 属性ccostcenterid的Setter方法.属性名：主产品成本中心
     * 创建日期:
     * 
     * @param newCcostcenterid java.lang.String
     */
    public void setCcostcenterid(java.lang.String newCcostcenterid) {
        this.setAttributeValue("ccostcenterid", newCcostcenterid);
    }

    /**
     * 属性cmaterialid的Getter方法.属性名：主产品
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCmaterialid() {
        return (java.lang.String) this.getAttributeValue("cmaterialid");
    }

    /**
     * 属性cmaterialid的Setter方法.属性名：主产品
     * 创建日期:
     * 
     * @param newCmaterialid java.lang.String
     */
    public void setCmaterialid(java.lang.String newCmaterialid) {
        this.setAttributeValue("cmaterialid", newCmaterialid);
    }

    /**
     * 属性cprojectid的Getter方法.属性名：项目
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCprojectid() {
        return (java.lang.String) this.getAttributeValue("cprojectid");
    }

    /**
     * 属性cprojectid的Setter方法.属性名：项目
     * 创建日期:
     * 
     * @param newCprojectid java.lang.String
     */
    public void setCprojectid(java.lang.String newCprojectid) {
        this.setAttributeValue("cprojectid", newCprojectid);
    }

    /**
     * 属性cvendorid的Getter方法.属性名：供应商
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCvendorid() {
        return (java.lang.String) this.getAttributeValue("cvendorid");
    }

    /**
     * 属性cvendorid的Setter方法.属性名：供应商
     * 创建日期:
     * 
     * @param newCvendorid java.lang.String
     */
    public void setCvendorid(java.lang.String newCvendorid) {
        this.setAttributeValue("cvendorid", newCvendorid);
    }

    /**
     * 属性cproductorid的Getter方法.属性名：生产厂商
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCproductorid() {
        return (java.lang.String) this.getAttributeValue("cproductorid");
    }

    /**
     * 属性cproductorid的Setter方法.属性名：生产厂商
     * 创建日期:
     * 
     * @param newCproductorid java.lang.String
     */
    public void setCproductorid(java.lang.String newCproductorid) {
        this.setAttributeValue("cproductorid", newCproductorid);
    }

    /**
     * 属性ccustomerid的Getter方法.属性名：客户
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCcustomerid() {
        return (java.lang.String) this.getAttributeValue("ccustomerid");
    }

    /**
     * 属性ccustomerid的Setter方法.属性名：客户
     * 创建日期:
     * 
     * @param newCcustomerid java.lang.String
     */
    public void setCcustomerid(java.lang.String newCcustomerid) {
        this.setAttributeValue("ccustomerid", newCcustomerid);
    }

    /**
     * 属性vfree1的Getter方法.属性名：自由辅助属性1
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree1() {
        return (java.lang.String) this.getAttributeValue("vfree1");
    }

    /**
     * 属性vfree1的Setter方法.属性名：自由辅助属性1
     * 创建日期:
     * 
     * @param newVfree1 java.lang.String
     */
    public void setVfree1(java.lang.String newVfree1) {
        this.setAttributeValue("vfree1", newVfree1);
    }

    /**
     * 属性vfree2的Getter方法.属性名：自由辅助属性2
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree2() {
        return (java.lang.String) this.getAttributeValue("vfree2");
    }

    /**
     * 属性vfree2的Setter方法.属性名：自由辅助属性2
     * 创建日期:
     * 
     * @param newVfree2 java.lang.String
     */
    public void setVfree2(java.lang.String newVfree2) {
        this.setAttributeValue("vfree2", newVfree2);
    }

    /**
     * 属性vfree3的Getter方法.属性名：自由辅助属性3
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree3() {
        return (java.lang.String) this.getAttributeValue("vfree3");
    }

    /**
     * 属性vfree3的Setter方法.属性名：自由辅助属性3
     * 创建日期:
     * 
     * @param newVfree3 java.lang.String
     */
    public void setVfree3(java.lang.String newVfree3) {
        this.setAttributeValue("vfree3", newVfree3);
    }

    /**
     * 属性vfree4的Getter方法.属性名：自由辅助属性4
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree4() {
        return (java.lang.String) this.getAttributeValue("vfree4");
    }

    /**
     * 属性vfree4的Setter方法.属性名：自由辅助属性4
     * 创建日期:
     * 
     * @param newVfree4 java.lang.String
     */
    public void setVfree4(java.lang.String newVfree4) {
        this.setAttributeValue("vfree4", newVfree4);
    }

    /**
     * 属性vfree5的Getter方法.属性名：自由辅助属性5
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree5() {
        return (java.lang.String) this.getAttributeValue("vfree5");
    }

    /**
     * 属性vfree5的Setter方法.属性名：自由辅助属性5
     * 创建日期:
     * 
     * @param newVfree5 java.lang.String
     */
    public void setVfree5(java.lang.String newVfree5) {
        this.setAttributeValue("vfree5", newVfree5);
    }

    /**
     * 属性vfree6的Getter方法.属性名：自由辅助属性6
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree6() {
        return (java.lang.String) this.getAttributeValue("vfree6");
    }

    /**
     * 属性vfree6的Setter方法.属性名：自由辅助属性6
     * 创建日期:
     * 
     * @param newVfree6 java.lang.String
     */
    public void setVfree6(java.lang.String newVfree6) {
        this.setAttributeValue("vfree6", newVfree6);
    }

    /**
     * 属性vfree7的Getter方法.属性名：自由辅助属性7
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree7() {
        return (java.lang.String) this.getAttributeValue("vfree7");
    }

    /**
     * 属性vfree7的Setter方法.属性名：自由辅助属性7
     * 创建日期:
     * 
     * @param newVfree7 java.lang.String
     */
    public void setVfree7(java.lang.String newVfree7) {
        this.setAttributeValue("vfree7", newVfree7);
    }

    /**
     * 属性vfree8的Getter方法.属性名：自由辅助属性8
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree8() {
        return (java.lang.String) this.getAttributeValue("vfree8");
    }

    /**
     * 属性vfree8的Setter方法.属性名：自由辅助属性8
     * 创建日期:
     * 
     * @param newVfree8 java.lang.String
     */
    public void setVfree8(java.lang.String newVfree8) {
        this.setAttributeValue("vfree8", newVfree8);
    }

    /**
     * 属性vfree9的Getter方法.属性名：自由辅助属性9
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree9() {
        return (java.lang.String) this.getAttributeValue("vfree9");
    }

    /**
     * 属性vfree9的Setter方法.属性名：自由辅助属性9
     * 创建日期:
     * 
     * @param newVfree9 java.lang.String
     */
    public void setVfree9(java.lang.String newVfree9) {
        this.setAttributeValue("vfree9", newVfree9);
    }

    /**
     * 属性vfree10的Getter方法.属性名：自由辅助属性10
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVfree10() {
        return (java.lang.String) this.getAttributeValue("vfree10");
    }

    /**
     * 属性vfree10的Setter方法.属性名：自由辅助属性10
     * 创建日期:
     * 
     * @param newVfree10 java.lang.String
     */
    public void setVfree10(java.lang.String newVfree10) {
        this.setAttributeValue("vfree10", newVfree10);
    }

    /**
     * 属性cbcostcenterid的Getter方法.属性名：材料成本中心
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCbcostcenterid() {
        return (java.lang.String) this.getAttributeValue("cbcostcenterid");
    }

    /**
     * 属性cbcostcenterid的Setter方法.属性名：材料成本中心
     * 创建日期:
     * 
     * @param newCbcostcenterid java.lang.String
     */
    public void setCbcostcenterid(java.lang.String newCbcostcenterid) {
        this.setAttributeValue("cbcostcenterid", newCbcostcenterid);
    }

    /**
     * 属性cbmaterialid的Getter方法.属性名：材料
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCbmaterialid() {
        return (java.lang.String) this.getAttributeValue("cbmaterialid");
    }

    /**
     * 属性cbmaterialid的Setter方法.属性名：材料
     * 创建日期:
     * 
     * @param newCbmaterialid java.lang.String
     */
    public void setCbmaterialid(java.lang.String newCbmaterialid) {
        this.setAttributeValue("cbmaterialid", newCbmaterialid);
    }

    /**
     * 属性cbprojectid的Getter方法.属性名：材料项目
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCbprojectid() {
        return (java.lang.String) this.getAttributeValue("cbprojectid");
    }

    /**
     * 属性cbprojectid的Setter方法.属性名：材料项目
     * 创建日期:
     * 
     * @param newCbprojectid java.lang.String
     */
    public void setCbprojectid(java.lang.String newCbprojectid) {
        this.setAttributeValue("cbprojectid", newCbprojectid);
    }

    /**
     * 属性cbvendorid的Getter方法.属性名：材料供应商
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCbvendorid() {
        return (java.lang.String) this.getAttributeValue("cbvendorid");
    }

    /**
     * 属性cbvendorid的Setter方法.属性名：材料供应商
     * 创建日期:
     * 
     * @param newCbvendorid java.lang.String
     */
    public void setCbvendorid(java.lang.String newCbvendorid) {
        this.setAttributeValue("cbvendorid", newCbvendorid);
    }

    /**
     * 属性cbproductorid的Getter方法.属性名：材料生产厂商
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCbproductorid() {
        return (java.lang.String) this.getAttributeValue("cbproductorid");
    }

    /**
     * 属性cbproductorid的Setter方法.属性名：材料生产厂商
     * 创建日期:
     * 
     * @param newCbproductorid java.lang.String
     */
    public void setCbproductorid(java.lang.String newCbproductorid) {
        this.setAttributeValue("cbproductorid", newCbproductorid);
    }

    /**
     * 属性cbcustomerid的Getter方法.属性名：材料客户
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCbcustomerid() {
        return (java.lang.String) this.getAttributeValue("cbcustomerid");
    }

    /**
     * 属性cbcustomerid的Setter方法.属性名：材料客户
     * 创建日期:
     * 
     * @param newCbcustomerid java.lang.String
     */
    public void setCbcustomerid(java.lang.String newCbcustomerid) {
        this.setAttributeValue("cbcustomerid", newCbcustomerid);
    }

    /**
     * 属性vbfree1的Getter方法.属性名：材料自由辅助属性1
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVbfree1() {
        return (java.lang.String) this.getAttributeValue("vbfree1");
    }

    /**
     * 属性vbfree1的Setter方法.属性名：材料自由辅助属性1
     * 创建日期:
     * 
     * @param newVbfree1 java.lang.String
     */
    public void setVbfree1(java.lang.String newVbfree1) {
        this.setAttributeValue("vbfree1", newVbfree1);
    }

    /**
     * 属性vbfree2的Getter方法.属性名：材料自由辅助属性2
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVbfree2() {
        return (java.lang.String) this.getAttributeValue("vbfree2");
    }

    /**
     * 属性vbfree2的Setter方法.属性名：材料自由辅助属性2
     * 创建日期:
     * 
     * @param newVbfree2 java.lang.String
     */
    public void setVbfree2(java.lang.String newVbfree2) {
        this.setAttributeValue("vbfree2", newVbfree2);
    }

    /**
     * 属性vbfree3的Getter方法.属性名：材料自由辅助属性3
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVbfree3() {
        return (java.lang.String) this.getAttributeValue("vbfree3");
    }

    /**
     * 属性vbfree3的Setter方法.属性名：材料自由辅助属性3
     * 创建日期:
     * 
     * @param newVbfree3 java.lang.String
     */
    public void setVbfree3(java.lang.String newVbfree3) {
        this.setAttributeValue("vbfree3", newVbfree3);
    }

    /**
     * 属性vbfree4的Getter方法.属性名：材料自由辅助属性4
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVbfree4() {
        return (java.lang.String) this.getAttributeValue("vbfree4");
    }

    /**
     * 属性vbfree4的Setter方法.属性名：材料自由辅助属性4
     * 创建日期:
     * 
     * @param newVbfree4 java.lang.String
     */
    public void setVbfree4(java.lang.String newVbfree4) {
        this.setAttributeValue("vbfree4", newVbfree4);
    }

    /**
     * 属性vbfree5的Getter方法.属性名：材料自由辅助属性5
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVbfree5() {
        return (java.lang.String) this.getAttributeValue("vbfree5");
    }

    /**
     * 属性vbfree5的Setter方法.属性名：材料自由辅助属性5
     * 创建日期:
     * 
     * @param newVbfree5 java.lang.String
     */
    public void setVbfree5(java.lang.String newVbfree5) {
        this.setAttributeValue("vbfree5", newVbfree5);
    }

    /**
     * 属性vbfree6的Getter方法.属性名：材料自由辅助属性6
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVbfree6() {
        return (java.lang.String) this.getAttributeValue("vbfree6");
    }

    /**
     * 属性vbfree6的Setter方法.属性名：材料自由辅助属性6
     * 创建日期:
     * 
     * @param newVbfree6 java.lang.String
     */
    public void setVbfree6(java.lang.String newVbfree6) {
        this.setAttributeValue("vbfree6", newVbfree6);
    }

    /**
     * 属性vbfree7的Getter方法.属性名：材料自由辅助属性7
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVbfree7() {
        return (java.lang.String) this.getAttributeValue("vbfree7");
    }

    /**
     * 属性vbfree7的Setter方法.属性名：材料自由辅助属性7
     * 创建日期:
     * 
     * @param newVbfree7 java.lang.String
     */
    public void setVbfree7(java.lang.String newVbfree7) {
        this.setAttributeValue("vbfree7", newVbfree7);
    }

    /**
     * 属性vbfree8的Getter方法.属性名：材料自由辅助属性8
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVbfree8() {
        return (java.lang.String) this.getAttributeValue("vbfree8");
    }

    /**
     * 属性vbfree8的Setter方法.属性名：材料自由辅助属性8
     * 创建日期:
     * 
     * @param newVbfree8 java.lang.String
     */
    public void setVbfree8(java.lang.String newVbfree8) {
        this.setAttributeValue("vbfree8", newVbfree8);
    }

    /**
     * 属性vbfree9的Getter方法.属性名：材料自由辅助属性9
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVbfree9() {
        return (java.lang.String) this.getAttributeValue("vbfree9");
    }

    /**
     * 属性vbfree9的Setter方法.属性名：材料自由辅助属性9
     * 创建日期:
     * 
     * @param newVbfree9 java.lang.String
     */
    public void setVbfree9(java.lang.String newVbfree9) {
        this.setAttributeValue("vbfree9", newVbfree9);
    }

    /**
     * 属性vbfree10的Getter方法.属性名：材料自由辅助属性10
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getVbfree10() {
        return (java.lang.String) this.getAttributeValue("vbfree10");
    }

    /**
     * 属性vbfree10的Setter方法.属性名：材料自由辅助属性10
     * 创建日期:
     * 
     * @param newVbfree10 java.lang.String
     */
    public void setVbfree10(java.lang.String newVbfree10) {
        this.setAttributeValue("vbfree10", newVbfree10);
    }

    /**
     * 属性celementid的Getter方法.属性名：核算要素
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCelementid() {
        return (java.lang.String) this.getAttributeValue("celementid");
    }

    /**
     * 属性celementid的Setter方法.属性名：核算要素
     * 创建日期:
     * 
     * @param newCelementid java.lang.String
     */
    public void setCelementid(java.lang.String newCelementid) {
        this.setAttributeValue("celementid", newCelementid);
    }

    /**
     * 属性cactivityid的Getter方法.属性名：作业
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCactivityid() {
        return (java.lang.String) this.getAttributeValue("cactivityid");
    }

    /**
     * 属性cactivityid的Setter方法.属性名：作业
     * 创建日期:
     * 
     * @param newCactivityid java.lang.String
     */
    public void setCactivityid(java.lang.String newCactivityid) {
        this.setAttributeValue("cactivityid", newCactivityid);
    }

    /**
     * 属性pk_group_actual的Getter方法.属性名：实际取价集团
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_group_actual() {
        return (java.lang.String) this.getAttributeValue("pk_group_actual");
    }

    /**
     * 属性pk_group_actual的Setter方法.属性名：实际取价集团
     * 创建日期:
     * 
     * @param newPk_group_actual java.lang.String
     */
    public void setPk_group_actual(java.lang.String newPk_group_actual) {
        this.setAttributeValue("pk_group_actual", newPk_group_actual);
    }

    /**
     * 属性pk_org_actual的Getter方法.属性名：实际取价工厂
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org_actual() {
        return (java.lang.String) this.getAttributeValue("pk_org_actual");
    }

    /**
     * 属性pk_org_actual的Setter方法.属性名：实际取价工厂
     * 创建日期:
     * 
     * @param newPk_org_actual java.lang.String
     */
    public void setPk_org_actual(java.lang.String newPk_org_actual) {
        this.setAttributeValue("pk_org_actual", newPk_org_actual);
    }

    /**
     * 属性isourcetype_actual的Getter方法.属性名：实际取价来源
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getIsourcetype_actual() {
        return (java.lang.Integer) this.getAttributeValue("isourcetype_actual");
    }

    /**
     * 属性isourcetype_actual的Setter方法.属性名：实际取价来源
     * 创建日期:
     * 
     * @param newIsourcetype_actual java.lang.Integer
     */
    public void setIsourcetype_actual(java.lang.Integer newIsourcetype_actual) {
        this.setAttributeValue("isourcetype_actual", newIsourcetype_actual);
    }

    /**
     * 属性cmaterialpriceid_actual的Getter方法.属性名：实际价格库
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCmaterialpriceid_actual() {
        return (java.lang.String) this.getAttributeValue("cmaterialpriceid_actual");
    }

    /**
     * 属性cmaterialpriceid_actual的Setter方法.属性名：实际价格库
     * 创建日期:
     * 
     * @param newCmaterialpriceid_actual java.lang.String
     */
    public void setCmaterialpriceid_actual(java.lang.String newCmaterialpriceid_actual) {
        this.setAttributeValue("cmaterialpriceid_actual", newCmaterialpriceid_actual);
    }

    /**
     * 属性pk_currtype_actual的Getter方法.属性名：实际币种
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_currtype_actual() {
        return (java.lang.String) this.getAttributeValue("pk_currtype_actual");
    }

    /**
     * 属性pk_currtype_actual的Setter方法.属性名：实际币种
     * 创建日期:
     * 
     * @param newPk_currtype_actual java.lang.String
     */
    public void setPk_currtype_actual(java.lang.String newPk_currtype_actual) {
        this.setAttributeValue("pk_currtype_actual", newPk_currtype_actual);
    }

    /**
     * 属性nprice的Getter方法.属性名：价格
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDouble
     */
    public nc.vo.pub.lang.UFDouble getNprice() {
        return (nc.vo.pub.lang.UFDouble) this.getAttributeValue("nprice");
    }

    /**
     * 属性nprice的Setter方法.属性名：价格
     * 创建日期:
     * 
     * @param newNprice nc.vo.pub.lang.UFDouble
     */
    public void setNprice(nc.vo.pub.lang.UFDouble newNprice) {
        this.setAttributeValue("nprice", newNprice);
    }

    /**
     * 属性errorinfo的Getter方法.属性名：错误原因
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getErrorinfo() {
        return (java.lang.String) this.getAttributeValue("errorinfo");
    }

    /**
     * 属性errorinfo的Setter方法.属性名：错误原因
     * 创建日期:
     * 
     * @param newErrorinfo java.lang.String
     */
    public void setErrorinfo(java.lang.String newErrorinfo) {
        this.setAttributeValue("errorinfo", newErrorinfo);
    }

    /**
     * 属性solveplan的Getter方法.属性名：解决方案
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getSolveplan() {
        return (java.lang.String) this.getAttributeValue("solveplan");
    }

    /**
     * 属性solveplan的Setter方法.属性名：解决方案
     * 创建日期:
     * 
     * @param newSolveplan java.lang.String
     */
    public void setSolveplan(java.lang.String newSolveplan) {
        this.setAttributeValue("solveplan", newSolveplan);
    }

    /**
     * 属性dr的Getter方法.属性名：dr
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getDr() {
        return (java.lang.Integer) this.getAttributeValue("dr");
    }

    /**
     * 属性dr的Setter方法.属性名：dr
     * 创建日期:
     * 
     * @param newDr java.lang.Integer
     */
    public void setDr(java.lang.Integer newDr) {
        this.setAttributeValue("dr", newDr);
    }

    /**
     * 属性ts的Getter方法.属性名：ts
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getTs() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("ts");
    }

    /**
     * 属性ts的Setter方法.属性名：ts
     * 创建日期:
     * 
     * @param newTs nc.vo.pub.lang.UFDateTime
     */
    public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
        this.setAttributeValue("ts", newTs);
    }

    /**
     * <p>
     * 取得父VO主键字段.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getParentPKFieldName() {
        return null;
    }

    /**
     * <p>
     * 取得表主键.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getPKFieldName() {
        return "pk_log";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getTableName() {
        return "mapub_acquirepricelog";
    }

    /**
     * 按照默认方式创建构造子.
     * 创建日期:
     */
    public AcquirePriceLogVO() {
        super();
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public static java.lang.String getDefaultTableName() {
        return "mapub_acquirepricelog";
    }

    @Override
    @nc.vo.annotation.MDEntityInfo(beanFullclassName = "nc.vo.mapub.acquirepricelog.entity.AcquirePriceLogVO")
    public IVOMeta getMetaData() {
        IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("mapub.mapub_acquirepricelog");
        return meta;
    }
}
