insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('0001ZA1000000000M4AZ',1,-1,'产品名称',null,0,0,null,-1,'N','cmaterialid',-1,'cmaterialid.name',0,'N',1,'N','Y',3,null,0,'name','uap.material_v.name',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,'1381001090014',null,'N',1,3,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000XAAZ',1,-1,'基本分类编码',null,0,1,null,-1,'N',null,-1,'cmarbaseclassid',0,'N',1,'N','Y',6,null,0,'cmarbaseclassid','cm.cm_allocfac_b.cmarbaseclassid',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,'物料基本分类,nl=N','1381001090037',null,'N',1,6,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001Z31000000000XAB0',1,-1,'基本分类名称',null,0,0,null,-1,'N','cmarbaseclassid',-1,'cmarbaseclassid.name',0,'N',1,'N','Y',7,null,0,'name','uap.marbasclass.name',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,'1381001090038',null,'N',1,7,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000002Z95',1,-1,'产品名称',null,0,0,null,-1,'N','cmaterialvid',-1,'cmaterialvid.name',0,'N',1,'N','N',17,null,0,'name','uap.material_v.name',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,'UC000-0000115',null,'N',0,17,'itempks',null,0,'2015-09-01 11:08:53','N',null,null,null,1,0,'N',0,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA1000000000602B',1,-1,null,'1',0,1,null,-1,'N',null,-1,'ialloctype',0,'N',1,'N','Y',3,null,0,'ialloctype','cm.cm_allocfac.ialloctype',null,'N',1,null,'1002ZA100000000034NN','@@@@',0,null,null,null,'N',1,3,'main','main',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008WZQ',1,-1,'产品编码',null,0,1,null,-1,'Y',null,-1,'cmaterialid',0,'N',1,'Y','Y',2,null,0,'cmaterialid','cm.cm_allocfac_b.cmaterialid',null,'N',1,null,'1002ZA100000000034NN','@@@@',1,null,'UC000-0000122',null,'N',1,2,'itempks','子表pks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008WZR',1,-1,'成本分类名称',null,0,0,null,-1,'N','cmarcostclassid',-1,'cmarcostclassid.name',0,'N',1,'N','Y',5,null,0,'name','uap.marcostclass.name',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,'1381001090002',null,'N',1,5,'itempks',null,0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008WZS',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',0,'N',1,'N','N',14,null,0,'pk_org_v','cm.cm_allocfac_b.pk_org_v',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',0,14,'itempks',null,0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',0,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008WZU',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',15,null,0,'ts','cm.cm_allocfac_b.ts',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',0,15,'itempks',null,0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008WZV',1,-1,'材料名称',null,0,0,null,-1,'N','cstuffid',-1,'cstuffid.name',0,'N',1,'N','Y',31,null,0,'name','uap.material.name',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,'1381001090017',null,'N',1,31,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008WZW',1,-1,'分配系数明细',null,0,1,null,-1,'N',null,-1,'callocfac_bid',0,'N',1,'N','N',11,null,0,'callocfac_bid','cm.cm_allocfac_b.callocfac_bid',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,'1381001090009',null,'N',0,11,'itempks',null,0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008WZX',1,-1,'产品编码',null,0,0,null,-1,'N',null,-1,'cmaterialvid',0,'N',1,'N','N',16,null,0,'cmaterialvid','cm.cm_allocfac_b.cmaterialvid',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,'UC000-0000122',null,'N',0,16,'itempks',null,0,'2015-09-01 11:08:53','N',null,null,null,0,0,'N',0,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008WZY',1,-1,'分配系数',null,0,1,null,-1,'N',null,-1,'callocfacid',0,'N',1,'N','N',10,null,0,'callocfacid','cm.cm_allocfac_b.callocfacid',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,'1381001090012',null,'N',0,10,'itempks',null,0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008WZZ',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',13,null,0,'pk_org','cm.cm_allocfac_b.pk_org',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',0,13,'itempks',null,0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',0,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008X00',1,-1,'作业编码',null,0,1,null,-1,'N',null,-1,'cactivityid',0,'N',1,'N','Y',8,null,0,'cactivityid','cm.cm_allocfac_b.cactivityid',null,'N',1,null,'1002ZA100000000034NN','@@@@',1,null,'1381001090003',null,'N',1,8,'itempks',null,0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008X02',1,-1,null,null,0,0,null,-1,'N','cactivityid',-1,'cactivityid.vactivityname',0,'N',1,'N','Y',9,null,0,'vactivityname','mmbd.bd_activity.vactivityname',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',1,9,'itempks',null,0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008X03',1,-1,'成本中心名称',null,0,0,null,-1,'N','ccostcenterid',-1,'ccostcenterid.ccname',0,'N',1,'N','Y',1,null,0,'ccname','resa.resacostcenter.ccname',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,'1381001090007',null,'N',1,1,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008X04',1,-1,'成本分类编码',null,0,1,null,-1,'N',null,-1,'cmarcostclassid',0,'N',1,'N','Y',4,null,0,'cmarcostclassid','cm.cm_allocfac_b.cmarcostclassid',null,'N',1,null,'1002ZA100000000034NN','@@@@',1,'物料成本分类,nl=N','1381001090004',null,'N',1,4,'itempks',null,0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008X05',1,-1,'集团',null,0,0,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',12,null,0,'pk_group','cm.cm_allocfac_b.pk_group',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,'UC001-0000072',null,'N',0,12,'itempks',null,0,'2015-09-01 11:08:53','N',null,null,null,0,1,'N',0,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008X07',1,-1,'成本中心编码',null,0,1,null,-1,'N',null,-1,'ccostcenterid',0,'N',1,'N','Y',0,null,0,'ccostcenterid','cm.cm_allocfac_b.ccostcenterid',null,'N',1,null,'1002ZA100000000034NN','@@@@',1,null,'1381001090006',null,'N',1,0,'itempks','子表pks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008X08',1,-1,null,null,0,1,null,-1,'N',null,-1,'nfactor',0,'N',1,'N','Y',33,null,0,'nfactor','cm.cm_allocfac_b.nfactor',null,'N',1,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',1,33,'itempks',null,0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000008X09',1,-1,'材料编码',null,0,1,null,-1,'N',null,-1,'cstuffid',0,'N',1,'N','Y',29,null,0,'cstuffid','cm.cm_allocfac_b.cstuffid',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,'1381001090016',null,'N',1,29,'itempks','子表pks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000042GDQ',1,-1,null,null,0,1,null,-1,'N',null,-1,'cprojectid',0,'N',1,'N','N',18,null,0,'cprojectid','cm.cm_allocfac_b.cprojectid',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,'项目,code=N',null,null,'N',0,18,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000042GDR',1,-1,null,null,0,1,null,-1,'N',null,-1,'cvendorid',0,'N',1,'N','N',19,null,0,'cvendorid','cm.cm_allocfac_b.cvendorid',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,'供应商档案,code=N',null,null,'N',0,19,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000042GDS',1,-1,null,null,0,1,null,-1,'N',null,-1,'ccustomerid',0,'N',1,'N','N',21,null,0,'ccustomerid','cm.cm_allocfac_b.ccustomerid',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,'客户档案,code=N',null,null,'N',0,21,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000042GDT',1,-1,null,null,0,1,null,-1,'N',null,-1,'cproductorid',0,'N',1,'N','N',20,null,0,'cproductorid','cm.cm_allocfac_b.cproductorid',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,'生产厂商(自定义档案),code=N',null,null,'N',0,20,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000042GDX',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree4',0,'N',1,'N','N',25,null,0,'vbfree4','cm.cm_allocfac_b.vbfree4',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',0,25,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000042GDY',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree2',0,'N',1,'N','N',23,null,0,'vbfree2','cm.cm_allocfac_b.vbfree2',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',0,23,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000042GDZ',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree10',0,'N',1,'N','N',34,null,0,'vbfree10','cm.cm_allocfac_b.vbfree10',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',0,34,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000042GE0',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree7',0,'N',1,'N','N',28,null,0,'vbfree7','cm.cm_allocfac_b.vbfree7',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',0,28,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000042GE1',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree6',0,'N',1,'N','N',27,null,0,'vbfree6','cm.cm_allocfac_b.vbfree6',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',0,27,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000042GE2',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree1',0,'N',1,'N','N',22,null,0,'vbfree1','cm.cm_allocfac_b.vbfree1',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',0,22,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000042GE3',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree9',0,'N',1,'N','N',32,null,0,'vbfree9','cm.cm_allocfac_b.vbfree9',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',0,32,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000042GE4',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree3',0,'N',1,'N','N',24,null,0,'vbfree3','cm.cm_allocfac_b.vbfree3',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',0,24,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000042GE5',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree5',0,'N',1,'N','N',26,null,0,'vbfree5','cm.cm_allocfac_b.vbfree5',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',0,26,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1001ZA10000000042GE6',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree8',0,'N',1,'N','N',30,null,0,'vbfree8','cm.cm_allocfac_b.vbfree8',null,'N',0,null,'1002ZA100000000034NN','@@@@',1,null,null,null,'N',0,30,'itempks','itempks',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA100000000034NQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'creationtime',null,'N',1,'N','Y',10,null,0,'creationtime','cm.cm_allocfac.creationtime',null,'N',0,null,'1002ZA100000000034NN',null,2,null,null,null,'N',1,1,'tail',null,0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA100000000034NT',1,-1,'分配系数名称',null,0,1,null,-1,'N',null,-1,'vname',null,'N',1,'N','Y',2,null,0,'vname','cm.cm_allocfac.vname',null,'N',1,null,'1002ZA100000000034NN',null,0,null,'1381001090001',null,'N',1,2,'main','main',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA100000000034NU',1,-1,null,null,0,0,null,-1,'N',null,-1,'creator',null,'N',1,'N','Y',9,null,0,'creator','cm.cm_allocfac.creator',null,'N',0,null,'1002ZA100000000034NN',null,2,null,null,null,'N',1,0,'tail','审计信息',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA100000000034NX',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifiedtime',null,'N',1,'N','Y',12,null,0,'modifiedtime','cm.cm_allocfac.modifiedtime',null,'N',0,null,'1002ZA100000000034NN',null,2,null,null,null,'N',1,3,'tail','审计信息',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA100000000034NY',1,-1,'分配系数',null,0,0,null,-1,'N',null,-1,'callocfacid',null,'N',1,'N','N',5,null,0,'callocfacid','cm.cm_allocfac.callocfacid',null,'N',0,null,'1002ZA100000000034NN',null,0,null,'1381001090012',null,'N',0,5,'main','main',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA100000000034NZ',1,-1,'分配系数编码',null,0,1,null,-1,'N',null,-1,'vcode',null,'N',1,'N','Y',1,null,0,'vcode','cm.cm_allocfac.vcode',null,'Y',1,null,'1002ZA100000000034NN',null,0,null,'1381001090005',null,'N',1,1,'main','main',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA100000000034O0',1,-1,null,null,0,1,null,-1,'N',null,-1,'vnote',null,'N',1,'N','Y',4,null,0,'vnote','cm.cm_allocfac.vnote',null,'N',0,null,'1002ZA100000000034NN',null,0,null,null,null,'N',1,4,'main','main',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA100000000034O1',1,-1,null,null,0,0,null,-1,'N',null,-1,'modifier',null,'N',1,'N','Y',11,null,0,'modifier','cm.cm_allocfac.modifier',null,'N',0,null,'1002ZA100000000034NN',null,2,null,null,null,'N',1,2,'tail','审计信息',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA100000000034O2',1,-1,'集团',null,0,0,null,-1,'N',null,-1,'pk_group',null,'N',1,'N','N',6,null,0,'pk_group','cm.cm_allocfac.pk_group',null,'N',0,null,'1002ZA100000000034NN',null,0,null,'UC001-0000072',null,'N',0,6,'main','main',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA100000000034O3',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_v',null,'N',1,'N','N',7,null,0,'pk_org_v','cm.cm_allocfac.pk_org_v',null,'N',0,null,'1002ZA100000000034NN',null,0,null,null,null,'N',0,7,'main','main',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA100000000034O4',1,-1,'业务单元',null,0,0,null,-1,'N',null,-1,'pk_org',null,'N',1,'N','N',0,null,0,'pk_org','cm.cm_allocfac.pk_org','pk_org_v=pk_vid','N',0,null,'1002ZA100000000034NN',null,0,'业务单元','UC000-000003',null,'N',0,0,'main','main',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',0,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002ZA10000000004BV6',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',8,null,0,'ts','cm.cm_allocfac.ts',null,'N',0,null,'1002ZA100000000034NN','@@@@',0,null,null,null,'N',0,8,'main','main',0,'2015-09-01 11:08:53','N',null,null,null,1,1,'N',1,null,1)
go

