insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z3100000000117MM',1,-1,null,null,0,1,null,-1,'N',null,-1,'isourcetype_actual',null,'N',1,'N','Y',0,null,0,'isourcetype_actual','mapub.mapub_acquirepricelog.isourcetype_actual',null,'N',1,null,'1002Z3100000000117ID',null,1,null,'138100110-0015',null,'N',1,22,'mapub_acquirepricelog','取价错误日志',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,120)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z3100000000117MQ',1,-1,null,null,0,0,null,-1,'N',null,-1,'pk_org_actual',null,'N',1,'N','N',0,null,0,'pk_org_actual','mapub.mapub_acquirepricelog.pk_org_actual',null,'N',0,null,'1002Z3100000000117ID',null,1,'工厂,code=N','138100110-0016',null,'N',0,8,'mapub_acquirepricelog','取价错误日志',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z3100000000117MS',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',null,'N',1,'N','N',0,null,0,'ts','mapub.mapub_acquirepricelog.ts',null,'N',0,null,'1002Z3100000000117ID',null,1,null,null,null,'N',0,5,'mapub_acquirepricelog','取价错误日志',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z3100000000117MW',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_log',null,'N',1,'N','N',0,null,0,'pk_log','mapub.mapub_acquirepricelog.pk_log',null,'N',0,null,'1002Z3100000000117ID',null,1,null,null,null,'N',0,1,'mapub_acquirepricelog','取价错误日志',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z3100000000117MX',1,-1,null,null,0,1,null,-1,'N',null,-1,'solveplan',null,'N',1,'N','Y',0,null,0,'solveplan','mapub.mapub_acquirepricelog.solveplan',null,'N',1,null,'1002Z3100000000117ID',null,1,null,null,null,'N',1,24,'mapub_acquirepricelog','取价错误日志',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,500)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z3100000000117N2',1,-1,null,null,0,1,null,-1,'N',null,-1,'errorinfo',null,'N',1,'N','Y',0,null,0,'errorinfo','mapub.mapub_acquirepricelog.errorinfo',null,'N',1,null,'1002Z3100000000117ID',null,1,null,null,null,'N',1,23,'mapub_acquirepricelog','取价错误日志',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,500)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z3100000000117N4',1,-1,null,null,0,1,null,-1,'N',null,-1,'prioritylevel',null,'N',1,'N','Y',0,null,0,'prioritylevel','mapub.mapub_acquirepricelog.prioritylevel',null,'N',1,null,'1002Z3100000000117ID',null,1,null,null,null,'N',1,21,'mapub_acquirepricelog','取价错误日志',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z3100000000117N6',1,-1,null,null,0,1,null,-1,'N',null,-1,'vacquiretype',null,'N',1,'N','N',0,null,0,'vacquiretype','mapub.mapub_acquirepricelog.vacquiretype',null,'N',0,null,'1002Z3100000000117ID',null,1,null,null,null,'N',0,2,'mapub_acquirepricelog','取价错误日志',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z3100000000117NE',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbmaterialid',null,'N',1,'N','Y',0,null,0,'cbmaterialid','mapub.mapub_acquirepricelog.cbmaterialid',null,'N',1,null,'1002Z3100000000117ID',null,1,'物料','138100110-0017',null,'N',1,3,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z3100000000117NF',1,-1,null,null,0,0,null,-1,'N','cbmaterialid',-1,'cbmaterialid.name',null,'N',1,'N','Y',0,null,0,'name','uap.material_v.name',null,'N',0,null,'1002Z3100000000117ID',null,1,null,null,null,'N',1,4,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000011GSA',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree3',0,'N',1,'N','N',0,null,0,'vbfree3','mapub.mapub_acquirepricelog.vbfree3',null,'N',0,null,'1002Z3100000000117ID','@@@@',1,null,null,null,'N',0,13,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000011GSB',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree1',0,'N',1,'N','N',0,null,0,'vbfree1','mapub.mapub_acquirepricelog.vbfree1',null,'N',0,null,'1002Z3100000000117ID','@@@@',1,null,null,null,'N',0,11,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000011GSC',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree7',0,'N',1,'N','N',0,null,0,'vbfree7','mapub.mapub_acquirepricelog.vbfree7',null,'N',0,null,'1002Z3100000000117ID','@@@@',1,null,null,null,'N',0,17,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000011GSD',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree2',0,'N',1,'N','N',0,null,0,'vbfree2','mapub.mapub_acquirepricelog.vbfree2',null,'N',0,null,'1002Z3100000000117ID','@@@@',1,null,null,null,'N',0,12,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000011GSE',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbprojectid',0,'N',1,'N','N',0,null,0,'cbprojectid','mapub.mapub_acquirepricelog.cbprojectid',null,'N',0,null,'1002Z3100000000117ID','@@@@',1,'项目,code=N',null,null,'N',0,6,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000011GSF',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree8',0,'N',1,'N','N',0,null,0,'vbfree8','mapub.mapub_acquirepricelog.vbfree8',null,'N',0,null,'1002Z3100000000117ID','@@@@',1,null,null,null,'N',0,18,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000011GSG',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbproductorid',0,'N',1,'N','N',0,null,0,'cbproductorid','mapub.mapub_acquirepricelog.cbproductorid',null,'N',0,null,'1002Z3100000000117ID','@@@@',1,'生产厂商(自定义档案),code=N',null,null,'N',0,9,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000011GSH',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbcustomerid',0,'N',1,'N','N',0,null,0,'cbcustomerid','mapub.mapub_acquirepricelog.cbcustomerid',null,'N',0,null,'1002Z3100000000117ID','@@@@',1,'客户档案,code=N',null,null,'N',0,10,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000011GSI',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree6',0,'N',1,'N','N',0,null,0,'vbfree6','mapub.mapub_acquirepricelog.vbfree6',null,'N',0,null,'1002Z3100000000117ID','@@@@',1,null,null,null,'N',0,16,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000011GSJ',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbvendorid',0,'N',1,'N','N',0,null,0,'cbvendorid','mapub.mapub_acquirepricelog.cbvendorid',null,'N',0,null,'1002Z3100000000117ID','@@@@',1,'供应商档案,code=N',null,null,'N',0,7,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000011GSK',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree10',0,'N',1,'N','N',0,null,0,'vbfree10','mapub.mapub_acquirepricelog.vbfree10',null,'N',0,null,'1002Z3100000000117ID','@@@@',1,null,null,null,'N',0,20,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000011GSL',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree5',0,'N',1,'N','N',0,null,0,'vbfree5','mapub.mapub_acquirepricelog.vbfree5',null,'N',0,null,'1002Z3100000000117ID','@@@@',1,null,null,null,'N',0,15,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000011GSM',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree4',0,'N',1,'N','N',0,null,0,'vbfree4','mapub.mapub_acquirepricelog.vbfree4',null,'N',0,null,'1002Z3100000000117ID','@@@@',1,null,null,null,'N',0,14,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000011GSN',1,-1,null,null,0,1,null,-1,'N',null,-1,'vbfree9',0,'N',1,'N','N',0,null,0,'vbfree9','mapub.mapub_acquirepricelog.vbfree9',null,'N',0,null,'1002Z3100000000117ID','@@@@',1,null,null,null,'N',0,19,'mapub_acquirepricelog','mapub_acquirepricelog',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,100)
go

