insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010Z17',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_org',0,'N',1,'N','N',0,null,0,'pk_org','mapub.mapub_materialpullprice.pk_org',null,'N',0,null,'1002Z310000000010VZR','@@@@',0,null,null,null,'N',0,3,'biaozhunchengben','biaozhunchengben',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010Z18',1,0,null,null,0,1,null,-1,'N',null,20,'pingjuncaigouruku',0,'N',1,'N','N',0,null,0,null,null,null,'N',0,null,'1002Z310000000010VZR','@@@@',0,null,'138100110-0009',null,'N',0,1,'pingjuncaigouruku','平均采购入库单价',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010Z19',1,-1,null,null,0,1,null,-1,'N',null,-1,'ts',0,'N',1,'N','N',0,null,0,'ts','mapub.mapub_materialpullprice.ts',null,'N',0,null,'1002Z310000000010VZR','@@@@',0,null,null,null,'N',0,2,'mapub_materialpullprice','物料取价',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010Z1A',1,-1,null,null,0,1,null,-1,'N',null,-1,'cperiodscheme',0,'N',1,'N','Y',0,null,0,'cperiodscheme','mapub.mapub_materialpullprice.cperiodscheme',null,'N',0,null,'1002Z310000000010VZR','@@@@',0,null,null,null,'N',1,1,'mapub_materialpullprice','物料取价',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010Z1B',1,-1,null,null,0,1,null,-1,'N',null,-1,'cperiod',0,'N',1,'N','Y',0,null,0,'cperiod','mapub.mapub_materialpullprice.cperiod',null,'N',1,null,'1002Z310000000010VZR','@@@@',0,null,'138100110-0010',null,'N',1,2,'zuixinjiecunjia','zuixinjiecunjia',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010Z1C',1,-1,null,null,0,1,null,-1,'N',null,-1,'costtype',0,'N',1,'N','Y',0,null,0,'costtype','mapub.mapub_materialpullprice.costtype',null,'N',1,null,'1002Z310000000010VZR','@@@@',0,null,null,null,'N',1,2,'biaozhunchengben','biaozhunchengben',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010Z1D',1,-1,null,null,0,1,null,-1,'N',null,-1,'cenddate',0,'N',1,'N','Y',0,null,0,'cenddate','mapub.mapub_materialpullprice.cenddate',null,'N',1,null,'1002Z310000000010VZR','@@@@',0,null,'138100110-0011',null,'N',1,3,'pingjuncaigouruku','pingjuncaigouruku',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010Z1E',1,-1,null,null,0,1,null,-1,'N',null,-1,'pk_group',0,'N',1,'N','N',0,null,0,'pk_group','mapub.mapub_materialpullprice.pk_group',null,'N',0,null,'1002Z310000000010VZR','@@@@',0,null,null,null,'N',0,4,'biaozhunchengben','biaozhunchengben',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010Z1F',1,0,null,null,0,1,null,-1,'N',null,20,'zuixinjiecunjia',0,'N',1,'N','N',0,null,0,null,null,null,'N',0,null,'1002Z310000000010VZR','@@@@',0,null,'138100110-0012',null,'N',0,1,'zuixinjiecunjia','最新结存价',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010Z1G',1,-1,null,null,0,1,null,-1,'N',null,-1,'cbegindate',0,'N',1,'N','Y',0,null,0,'cbegindate','mapub.mapub_materialpullprice.cbegindate',null,'N',1,null,'1002Z310000000010VZR','@@@@',0,null,'138100110-0013',null,'N',1,2,'pingjuncaigouruku','pingjuncaigouruku',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,1)
go

insert into pub_billtemplet_b(pk_billtemplet_b,cardflag,datatype,defaultshowname,defaultvalue,dr,editflag,editformula,foreground,hyperlinkflag,idcolname,inputlength,itemkey,itemtype,leafflag,listflag,listhyperlinkflag,listshowflag,listshoworder,loadformula,lockflag,metadatapath,metadataproperty,metadatarelation,newlineflag,nullflag,options,pk_billtemplet,pk_corp,pos,reftype,resid,resid_tabname,reviseflag,showflag,showorder,table_code,table_name,totalflag,ts,userdefflag,userdefine1,userdefine2,userdefine3,usereditflag,userflag,userreviseflag,usershowflag,validateformula,width) values('1002Z310000000010Z1H',1,0,null,null,0,1,null,-1,'N',null,20,'biaozhunchengben',0,'N',1,'N','N',0,null,0,null,null,null,'N',0,null,'1002Z310000000010VZR','@@@@',0,null,'138100110-0014',null,'N',0,1,'biaozhunchengben','标准成本',0,'2015-04-21 11:31:47','N',null,null,null,1,1,'N',1,null,1)
go

