insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value,ext1) values('1003ZA1000000000C5I8','业务单元',5,1,1,null,null,'pk_org','业务单元',null,'N','Y','N','Y','N','N','N','N','Y','N','N','N','N','Y','Y',null,'Y',9999,null,'==@','等于@',0,'@@@@','1003ZA1000000000C5I6',null,'1381001090030',2,null,null,'2015-04-21 11:31:48','N','#mainorg#',null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value,ext1) values('1003ZA1000000000C5I9','IM,073aa2b7-0127-4a80-a94e-a14db7ab6e60',6,2,1,null,null,'ialloctype',null,null,'N','Y','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=@','等于@',0,'@@@@','1003ZA1000000000C5I6',null,null,2,null,null,'2015-04-21 11:31:48','N',null,null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value,ext1) values('1003ZA1000000000C5IA','-99',0,3,1,null,null,'vcode','分配系数编码',null,'N','N','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1003ZA1000000000C5I6',null,'1381001090005',2,null,null,'2015-04-21 11:31:48','N',null,null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value,ext1) values('1003ZA1000000000C5IB','-99',9,4,1,null,null,'vname','分配系数名称',null,'N','N','N','Y','N','N','N',null,'N','N','N','N','N','N','Y',null,'Y',9999,null,'=@left like@','等于@左包含@',0,'@@@@','1003ZA1000000000C5I6',null,'1381001090001',2,null,null,'2015-04-21 11:31:48','N',null,null)
go

insert into pub_query_condition(id,consult_code,data_type,disp_sequence,disp_type,disp_value,dr,field_code,field_name,guideline,if_attrrefused,if_autocheck,if_datapower,if_default,if_desc,if_group,if_immobility,if_multicorpref,if_must,if_notmdcondition,if_order,if_subincluded,if_sum,if_sysfuncrefused,if_used,instrumentsql,iscondition,limits,max_length,opera_code,opera_name,order_sequence,pk_corp,pk_templet,prerestrict,resid,return_type,table_code,table_name,ts,userdefflag,value,ext1) values('1012ZA10000000000R09','管控范围',5,0,1,null,null,'ccontrolscope','管控范围',null,'N','Y','N','Y','N','N','N','N','Y','Y','N','N','N','Y','N',null,'N',9999,null,'==@','等于@',0,'@@@@','1003ZA1000000000C5I6',null,'1381001090010',2,null,null,'2015-04-21 11:31:48','N','#maincontrolarea#',null)
go

