/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.mapub.coprodcoef.entity;

import nc.vo.pub.IVOMeta;
import nc.vo.pub.SuperVO;
import nc.vo.pubapp.pattern.model.meta.entity.vo.VOMetaFactory;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 * 在此处添加此类的描述信息
 * </p>
 * 创建日期:
 * 
 * @author
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class CoprodcoefItemVO extends SuperVO {

    public static final String CCOPRODCOEFBID = "ccoprodcoefbid";

    public static final String CCOPRODCOEFID = "ccoprodcoefid";

    public static final String PK_GROUP = "pk_group";

    public static final String PK_ORG = "pk_org";

    public static final String PK_ORG_V = "pk_org_v";

    public static final String CMATERIALID = "cmaterialid";

    public static final String CMATERIALVID = "cmaterialvid";

    public static final String IPRODUCTTYPE = "iproducttype";

    public static final String CCOSTCENTERID = "ccostcenterid";

    public static final String CCOSTTYPEID = "ccosttypeid";

    public static final String CELEMENTID = "celementid";

    public static final String NRELCOEFFICIENT = "nrelcoefficient";

    /**
     * 属性ccoprodcoefbid的Getter方法.属性名：联产品相对系数明细
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCcoprodcoefbid() {
        return (java.lang.String) this.getAttributeValue("ccoprodcoefbid");
    }

    /**
     * 属性ccoprodcoefbid的Setter方法.属性名：联产品相对系数明细
     * 创建日期:
     * 
     * @param newCcoprodcoefbid java.lang.String
     */
    public void setCcoprodcoefbid(java.lang.String newCcoprodcoefbid) {
        this.setAttributeValue("ccoprodcoefbid", newCcoprodcoefbid);
    }

    /**
     * 属性ccoprodcoefid的Getter方法.属性名：联产品相对系数
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCcoprodcoefid() {
        return (java.lang.String) this.getAttributeValue("ccoprodcoefid");
    }

    /**
     * 属性ccoprodcoefid的Setter方法.属性名：联产品相对系数
     * 创建日期:
     * 
     * @param newCcoprodcoefid java.lang.String
     */
    public void setCcoprodcoefid(java.lang.String newCcoprodcoefid) {
        this.setAttributeValue("ccoprodcoefid", newCcoprodcoefid);
    }

    /**
     * 属性pk_group的Getter方法.属性名：集团
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_group() {
        return (java.lang.String) this.getAttributeValue("pk_group");
    }

    /**
     * 属性pk_group的Setter方法.属性名：集团
     * 创建日期:
     * 
     * @param newPk_group java.lang.String
     */
    public void setPk_group(java.lang.String newPk_group) {
        this.setAttributeValue("pk_group", newPk_group);
    }

    /**
     * 属性pk_org的Getter方法.属性名：工厂
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org() {
        return (java.lang.String) this.getAttributeValue("pk_org");
    }

    /**
     * 属性pk_org的Setter方法.属性名：工厂
     * 创建日期:
     * 
     * @param newPk_org java.lang.String
     */
    public void setPk_org(java.lang.String newPk_org) {
        this.setAttributeValue("pk_org", newPk_org);
    }

    /**
     * 属性pk_org_v的Getter方法.属性名：工厂版本
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getPk_org_v() {
        return (java.lang.String) this.getAttributeValue("pk_org_v");
    }

    /**
     * 属性pk_org_v的Setter方法.属性名：工厂版本
     * 创建日期:
     * 
     * @param newPk_org_v java.lang.String
     */
    public void setPk_org_v(java.lang.String newPk_org_v) {
        this.setAttributeValue("pk_org_v", newPk_org_v);
    }

    /**
     * 属性cmaterialid的Getter方法.属性名：物料最新版本
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCmaterialid() {
        return (java.lang.String) this.getAttributeValue("cmaterialid");
    }

    /**
     * 属性cmaterialid的Setter方法.属性名：物料最新版本
     * 创建日期:
     * 
     * @param newCmaterialid java.lang.String
     */
    public void setCmaterialid(java.lang.String newCmaterialid) {
        this.setAttributeValue("cmaterialid", newCmaterialid);
    }

    /**
     * 属性cmaterialvid的Getter方法.属性名：物料
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCmaterialvid() {
        return (java.lang.String) this.getAttributeValue("cmaterialvid");
    }

    /**
     * 属性cmaterialvid的Setter方法.属性名：物料
     * 创建日期:
     * 
     * @param newCmaterialvid java.lang.String
     */
    public void setCmaterialvid(java.lang.String newCmaterialvid) {
        this.setAttributeValue("cmaterialvid", newCmaterialvid);
    }

    /**
     * 属性iproducttype的Getter方法.属性名：产品类型
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getIproducttype() {
        return (java.lang.Integer) this.getAttributeValue("iproducttype");
    }

    /**
     * 属性iproducttype的Setter方法.属性名：产品类型
     * 创建日期:
     * 
     * @param newIproducttype java.lang.Integer
     */
    public void setIproducttype(java.lang.Integer newIproducttype) {
        this.setAttributeValue("iproducttype", newIproducttype);
    }

    /**
     * 属性ccostcenterid的Getter方法.属性名：成本中心
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCcostcenterid() {
        return (java.lang.String) this.getAttributeValue("ccostcenterid");
    }

    /**
     * 属性ccostcenterid的Setter方法.属性名：成本中心
     * 创建日期:
     * 
     * @param newCcostcenterid java.lang.String
     */
    public void setCcostcenterid(java.lang.String newCcostcenterid) {
        this.setAttributeValue("ccostcenterid", newCcostcenterid);
    }

    /**
     * 属性ccosttypeid的Getter方法.属性名：成本类型
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCcosttypeid() {
        return (java.lang.String) this.getAttributeValue("ccosttypeid");
    }

    /**
     * 属性ccosttypeid的Setter方法.属性名：成本类型
     * 创建日期:
     * 
     * @param newCcosttypeid java.lang.String
     */
    public void setCcosttypeid(java.lang.String newCcosttypeid) {
        this.setAttributeValue("ccosttypeid", newCcosttypeid);
    }

    /**
     * 属性celementid的Getter方法.属性名：核算要素编码
     * 创建日期:
     * 
     * @return java.lang.String
     */
    public java.lang.String getCelementid() {
        return (java.lang.String) this.getAttributeValue("celementid");
    }

    /**
     * 属性celementid的Setter方法.属性名：核算要素编码
     * 创建日期:
     * 
     * @param newCelementid java.lang.String
     */
    public void setCelementid(java.lang.String newCelementid) {
        this.setAttributeValue("celementid", newCelementid);
    }

    /**
     * 属性nrelcoefficient的Getter方法.属性名：相对系数
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDouble
     */
    public nc.vo.pub.lang.UFDouble getNrelcoefficient() {
        return (nc.vo.pub.lang.UFDouble) this.getAttributeValue("nrelcoefficient");
    }

    /**
     * 属性nrelcoefficient的Setter方法.属性名：相对系数
     * 创建日期:
     * 
     * @param newNrelcoefficient nc.vo.pub.lang.UFDouble
     */
    public void setNrelcoefficient(nc.vo.pub.lang.UFDouble newNrelcoefficient) {
        this.setAttributeValue("nrelcoefficient", newNrelcoefficient);
    }

    /**
     * 属性dr的Getter方法.属性名：dr
     * 创建日期:
     * 
     * @return java.lang.Integer
     */
    public java.lang.Integer getDr() {
        return (java.lang.Integer) this.getAttributeValue("dr");
    }

    /**
     * 属性dr的Setter方法.属性名：dr
     * 创建日期:
     * 
     * @param newDr java.lang.Integer
     */
    public void setDr(java.lang.Integer newDr) {
        this.setAttributeValue("dr", newDr);
    }

    /**
     * 属性ts的Getter方法.属性名：ts
     * 创建日期:
     * 
     * @return nc.vo.pub.lang.UFDateTime
     */
    public nc.vo.pub.lang.UFDateTime getTs() {
        return (nc.vo.pub.lang.UFDateTime) this.getAttributeValue("ts");
    }

    /**
     * 属性ts的Setter方法.属性名：ts
     * 创建日期:
     * 
     * @param newTs nc.vo.pub.lang.UFDateTime
     */
    public void setTs(nc.vo.pub.lang.UFDateTime newTs) {
        this.setAttributeValue("ts", newTs);
    }

    /**
     * <p>
     * 取得父VO主键字段.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getParentPKFieldName() {
        return null;
    }

    /**
     * <p>
     * 取得表主键.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getPKFieldName() {
        return "ccoprodcoefbid";
    }

    /**
     * <p>
     * 返回表名称.
     * <p>
     * 创建日期:
     * 
     * @return java.lang.String
     */
    @Override
    public java.lang.String getTableName() {
        return "mapub_coprodcoef_b";
    }

    /**
     * 按照默认方式创建构造子.
     * 创建日期:
     */
    public CoprodcoefItemVO() {
        super();
    }

    @Override
    @nc.vo.annotation.MDEntityInfo(beanFullclassName = "nc.vo.mapub.coprodcoef.entity.CoprodcoefItemVO")
    public IVOMeta getMetaData() {
        IVOMeta meta = VOMetaFactory.getInstance().getVOMeta("mapub.mapub_coprodcoef_b");
        return meta;
    }

    /**
     * @return
     */
    public static String getDefaultTableName() {
        return "mapub_coprodcoef_b";
    }
}
